### ISSUE TITLE
WF: Return the available states of a given CEI

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#102]
Create a service and API that returns the list of states available for a given CEI. To build this list EL must be evaluated for all transitions with current status as origin.

We need to evaluate every transition of the workflow base on the CEI.
 
For example, you have:
A CEI with code='xxx',
 
2 transitions:
NEW -> ACTIVE, with EL event.code='xxx',
NEW -> REJECTED, with EL event.code='yyy'
 
Then only the ACTIVE state should be returned.

--

The association should be inverted : it is not the CET that own a list of WF, it is a WF that is associated to a couple (CET,CFT) where the CFT is a list of String (that will play the roles of state).

Example :
I create a CET "project" with the following CFT

    name, String
    createDate, Date
    description, String
    status, List of String (NEW,ONGOING,CLOSED) with default value NEW

Then i create a workflow with code "Projet_cycle", i need to choose a CET in a drop list (not a script), i choose "Person", then it list me in another dropdown all the CFT of Person that have type List of String and a default value, i choose "status".
Then i can create the transitions and the actions.

When i update a CEI of type "Person" then in the beforeUpdate method meveo will check if the "status" value has changed, if yes then it will check if a WF exist for this CET and CFT then apply it like written in the description of the ticket.

--

The getState API should have 2 parameters : CEI's uuid  and CFT code.
It loads the CEI, then evaluate all the transition rules whose origin is the state (the value of the CFT in the CEI) and return the list of target states for all those transition whose rule evaluated to true.

**Comment by phubach** [comment]
Postman to test: [StatesOfCet.postman_collection.zip](https://github.com/meveo-org/meveo/files/5173241/StatesOfCet.postman_collection.zip)

**Comment by czetsuya** [comment]
@phubach why do we have to loop thru all the workflows to get the cet states, can't we use a query?

**Comment by phubach** [comment]
Update postman: [StatesOfCet.postman_collection.zip](https://github.com/meveo-org/meveo/files/5207495/StatesOfCet.postman_collection.zip)

**Comment by czetsuya** [comment]
Postman throws:

{
    "status": "FAIL",
    "errorCode": "ACTION_FORBIDDEN",
    "message": "User does not have permission 'CE_states-read'"
}

**Comment by phubach** [comment]
Update postman: [StateOfCEI.postman_collection.zip](https://github.com/meveo-org/meveo/files/5236790/StateOfCEI.postman_collection.zip)

**Comment by czetsuya** [comment]
Update the postman collection such that it test evaluating the transitions EL given the current status of the origin.

**Comment by phubach** [comment]
Update postman: [StateOfCEI.postman_collection.zip](https://github.com/meveo-org/meveo/files/5384063/StateOfCEI.postman_collection.zip)

**Comment by phubach** [comment]
Update postman: [StateOfCEI.postman_collection.zip](https://github.com/meveo-org/meveo/files/5384194/StateOfCEI.postman_collection.zip)
Video to test unique custom entity and custom field in WF: [Ticket102.zip](https://github.com/meveo-org/meveo/files/5384202/Ticket102.zip)

**Comment by ClementBareth** [comment]
@czetsuya can you test this please ?

**Comment by czetsuya** [comment]
For testing.
