### ISSUE TITLE
CEI update does not save code and description

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#108]
**Describe the bug**
When a CEI from a CET with storeAsTable=true is save, the code and description in the first tab are not save.

**To Reproduce**
1. Create a new CET, add at least 1 CFT
2. Create a new CEI, fill the code and description in the first tab as well as the CFT created
3. Hit save
4. Open the newly created CEI
5. Code and description fields are empty

**Expected behavior**
Code and description, should be save and displayed.

**Comment by ClementBareth** [comment]
@czetsuya this is a normal behavior. Only cfts are registred, so if you need these info you need to have "code" and "description" cfts.

I think we should better remove these fields in case the CET is not stored in the SQL single table

**Comment by czetsuya** [comment]
@ClementBareth ok. I'll implement that in this ticket.
