### ISSUE TITLE
NPE when installing a module

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#117]
**Describe the bug**
When installing a module, a NullPointerException is thrown.

**To Reproduce**
1. Go to `Configuration > Modules`
2. Import and Install a module that contains CETs, Scripts, and Endpoints,
3. A NPE is thrown.

**Expected behavior**
The module is imported and installed without errors

**Screenshots**
![image](https://user-images.githubusercontent.com/6660853/90101682-c0911d00-dd71-11ea-980a-ecd00a5ba800.png)

**Additional context**
Full logs: 
[server.zip](https://github.com/meveo-org/meveo/files/5067461/server.zip)

**Comment by tonysviews** [comment]
Still unable to install a module.  The error is now showing LazyInitializationException.
[server.log](https://github.com/meveo-org/meveo/files/5082302/server.log)

**Comment by ClementBareth** [comment]
Still not able to reproduce ...

![image](https://user-images.githubusercontent.com/14770781/90413575-ee969a00-e0ae-11ea-8607-85dcb7097c60.png)
