### ISSUE TITLE
[4312] Unable to access endpoint interface

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#12]
When accessing the generated endpoint interface file, the following error is displayed: <code>java.lang.NullPointerException</code> with the following error in the log:
<pre><code>
2020-06-11 10:56:01,677 ERROR [org.jboss.as.ejb3.invocation] (default task-37) WFLYEJB0034: EJB Invocation failed on component EndpointSchemaService for method public java.lang.String org.meveo.service.technicalservice.endpoint.schema.EndpointSchemaService.generateResponseSchema(org.meveo.model.technicalservice.endpoint.Endpoint): javax.ejb.EJBTransactionRolledbackException
</code></pre>

*Full log:* [[file:dCUSyMQ8ur6OKPbK8JiBFu|server.log]]

Steps to recreate:
*Create new script*
1. Go to Services > Scripts
2. New
3. Description: ListInvestigations Script
4. Class name: ListInvestigations
5. Save

*Create endpoint*
1. Go to Services > Endpoint
2. New
3. Name: list-investigations
4. Function code: ListInvestigations Script
5. Description: ListInvestigations Endpoint
6. Method: GET
7. Save

*Ensure that endpoint and endpoint interface urls are accessible:*
1. endpoint url: http://localhost:8080/meveo/rest/list-investigations
2. endpoint-interface url: http://localhost:8080/meveo/api/rest/endpoint/list-investigations.js

*Edit the ListInvestigations.java script*
1. Go to Services > Scripts and click on ListInvestigations
2. use the following code as the new script:
<pre><code>
package org.meveo.script;

import java.util.Map;

import org.meveo.service.script.Script;
import org.meveo.admin.exception.BusinessException;

public class ListInvestigations extends Script {
  private String result = "";

  public String getResult() {
    return result;
  }

  public void setResult(String result) {
    this.result = result;
  }
	
  @Override
  public void execute(Map<String, Object> parameters) throws BusinessException {
    super.execute(parameters);
    result = "This is a test response";
  }	
}
</code></pre>

3. Save

*Set the return value of the endpoint*
1. Go to Services > Endpoint and click on list-investigations
2. Select "result" as the Return Value Name.  (Set any value for the Parameter mappings default value)
3. Save.

*Again, ensure that endpoint and endpoint interface urls are accessible:*
1. endpoint url: http://localhost:8080/meveo/rest/list-investigations
2. endpoint-interface url: http://localhost:8080/meveo/api/rest/endpoint/list-investigations.js

**Comment by phubach** [comment]
@czetsuya I cannot reproduce java.lang.NullPointerException issue as steps reproduce anymore. But I found out another issue related load last data instead of latest data. I think we already have this issue in updating module and endpoint. Please check and create new ticket for it

**Comment by czetsuya** [comment]
@phubach It's a regression bug that is now fixed in develop branch.

**Comment by czetsuya** [comment]
I found the issue here. You must test with params in your endpoint.
