### ISSUE TITLE
Add inheritance to generated JSON schema

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#126]
**Is your feature request related to a problem? Please describe.**
When validating data using the JSON schema generated when a CET is created/updated, the validation is incomplete when the entity inherits some of its properties from a parent entity.

**Describe the solution you'd like**
The generated JSON schema should reflect the inheritance of properties between child and parent entities.

**Describe alternatives you've considered**
The JSON Schema standard does not define inheritance [Explain why inheritance isn't the right model](https://github.com/json-schema-org/json-schema-org.github.io/issues/148)

However, it is possible to validate a schema using the `allOf` property, which could be enough for our purposes of doing validation of data from the frontend: [How to do inheritance?](https://github.com/json-schema-org/json-schema-spec/issues/348)

**Additional context**
N/A

**Comment by ClementBareth** [comment]
@tonysviews I let you test
