### ISSUE TITLE
[4316] Endpoint interface javascript refactoring

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#13]
When an endpoint is created or updated, an endpoint interface javascript file is being generated.  The following changes should be made when generating the endpoint interface file.

1. The <code>EndpointInterface.js</code> should be generated.  Here is a sample of this file (will be updated as needed): 
* [EndpointInterface.txt](https://github.com/meveo-org/meveo/files/4824974/EndpointInterface.txt) _(rename file with .js extension)_

Make sure this is accessible at <code>{meveo.url}/api/rest/endpoint/EndpointInterface.js</code>
When an endpoint is created/updated, check if this file has already been generated.  If it does not exist, generate it before generating the endpoint interface code as described below.

2. The specific endpoint interface code should be similar to:
* [GetInvestigation.js](https://github.com/meveo-org/meveo/files/4818077/GetInvestigation.txt) _(rename file with .js extension)_
* [ListInvestigations.js](https://github.com/meveo-org/meveo/files/4818081/ListInvestigations.txt) _(rename file with .js extension)_
* [NewInvestigation.js](https://github.com/meveo-org/meveo/files/4818086/NewInvestigation.txt) _(rename file with .js extension)_

This should be generated whenever an endpoint is created/edited

To test, the module needs to be imported and the <code>executeApiCall()</code> method should be called from the frontend application e.g.
<pre><code>

// define the importmap, this is optional
<script type="importmap-shim">
  {
    "imports": {
      "ListInvestigations": "/meveo/api/rest/endpoint/ListInvestigations.js",
      "GetInvestigation": "/meveo/api/rest/endpoint/GetInvestigation.js"
    }
  }
</script>

import ListInvestigations from "ListInvestigations";
// if not using an import map, it can be imported using:
// import ListInvestigations from "/meveo/api/rest/endpoint/ListInvestigations.js";

import GetInvestigation from "GetInvestigation";
// if not using an import map, it can be imported using: 
// import GetInvestigation from "/meveo/api/rest/endpoint/GetInvestigation.js";

// getting the request and response schemas:

ListInvestigations.getRequestSchema();
GetInvestigation.getRequestSchema();

ListInvestigations.getResponseSchema();
GetInvestigation.getResponseSchema();

// calling the APIs

ListInvestigations.executeApiCall(
  this, /* the component that will receive the response */
  { noAuth: true, limit: 20, offset: 2 }, /* parameters for the request */
  this.updateInvestigationList, /* success callback */
  this.handleError /* error callback */
);

GetInvestigation.executeApiCall(
  this,
  { noAuth: true, id: "Investigation-123456" },
  this.updateInvestigation,
  this.handleError
);

</code></pre>

Test on https://github.com/webdrone-fr/module-socialprofile/tree/develop/meveo_module.

**Comment by tonysviews** [comment]
The endpoint URL being used in EndpointInterface.js is incorrect.
The correct URL should be:
<code>/meveo/rest/endpoint/{endpointCode}</code>
But the EndpointInterface uses:
<code>`#{API_BASE_URL}/api/rest/endpoint/${name}`</code>

Basically, the URL should start with <code>/meveo/rest</code> and not <code>/meveo/api/rest</code>
