### ISSUE TITLE
CET creation api throws 401 error

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#138]
**Describe the bug**
When i try to create a CET using postman (https://github.com/manaty/hellotodo/tree/master/meveo/postman) I encounter a 401 error.

**To Reproduce**
1. Download the postman collection from the URL above
2. Open Postman and import the collection
3. Run Login folder
4. Run Create CETs folder
5. It will throw a 401 exception

**Expected behavior**
The CETs should be properly created.

**Comment by anaxdev** [comment]
I have pulled the latest docker images up. And I have installed docker containers from scratch on my local. 
However, I couldn't reproduce this bug.

**Comment by anaxdev** [comment]
The problem was because the postman has used "localhost" for keycloak/meveo hostname. (in postman environment variables)
After change it by local IP address, this issue is not happened.
