### ISSUE TITLE
Add Git Repository to module

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#142]
**Is your feature request related to a problem? Please describe.**
Allow adding a git repository to a module

**Describe the solution you'd like**
Add a section in the Module form to add a git repository.
Add an Add to Module button on the Git Repository details.

**Comment by tonysviews** [comment]
@ClementBareth - It appears that it creates a zip file that includes the full git repository contents when exporting the module.  Is it possible that instead of including the full repository, it just uses the json details to clone the repository?  That should make the module simpler to export and install.

**Comment by ClementBareth** [comment]
@tonysviews You can still remove the files from module to avoid exporting them
