### ISSUE TITLE
Add new and attach Child entity on CEI for CET store as table

### ISSUE THREAD

**Issue by phubach** [meveo-org/meveo#143]
**Describe the bug**
Cannot add new and attach Child entity on CEI for CET store as table.

**To Reproduce**
1. Import and install module [TODOModule.json.txt](https://github.com/meveo-org/meveo/files/5127438/TODOModule.json.txt)
2. Create  a CEI TODOITEM
3. Click "New" button CEI TODOLIST
4. Click "Attach New" button
5. It will show popup does not have child entity
6. Click "Add New" button in CEI TODOLIST
7. Filter fields and click "Save" button
8. Save CEI TODOLIST
9. It cannot save new child entity to CEI TODOITEM
Video to reproduce: [ChildEntity.zip](https://github.com/meveo-org/meveo/files/5127476/ChildEntity.zip)

**Expected behavior**
- Popup of CEI TODOLIST should contain child entities.
- A new CEI TODOITEM should created when saving a new child entity from CEI TODOLIST

**Comment by czetsuya** [comment]
Clicking the "Attach New" button produced:

```
Caused by: java.lang.NullPointerException
	at deployment.meveo.war//org.meveo.admin.action.admin.custom.CustomEntityInstanceBean.initEntity(CustomEntityInstanceBean.java:110)
```

**Comment by phubach** [comment]
@czetsuya I cannot reproduce issue 
[Ticket143.zip](https://github.com/meveo-org/meveo/files/5200659/Ticket143.zip)
