### ISSUE TITLE
Incorrect class type for Custom Entity Template

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#15]
Steps:

1. Create a new Custom Entity: Ontology > Entity customization
2. Click New button
3. Fill out the fields
4. Click Save button
5. Click the + button under the Entity fields and Actions section
6. Fill out the form with the following details to create a custom field of "**Selection from list**" type:
![image](https://user-images.githubusercontent.com/6660853/85126133-6dae5400-b25f-11ea-8672-e4883a75b527.png)
7. Click Save button

The generated java code for this CET will have:

![image](https://user-images.githubusercontent.com/6660853/85126236-a5b59700-b25f-11ea-8ae6-ec1cebd6af3e.png)
![image](https://user-images.githubusercontent.com/6660853/85126255-b36b1c80-b25f-11ea-967c-d1393289003d.png)

Here is a test module with the described issue: 
[TestModule_version-0_0_1.txt](https://github.com/meveo-org/meveo/files/4804206/TestModule_version-0_0_1.txt)
(rename file to .json to import into meveo)

**Comment by czetsuya** [comment]
@tonysviews I've tested this ticket and you can use this feature now.

**Comment by tonysviews** [comment]
When declaring a CFT of type Double, the generated code assigns it as Long instead.

To recreate: 
1. Import and install the [Profile Module](https://github.com/webdrone-fr/module-socialprofile/blob/develop/meveo_module/ProfilesModule_version-0_0_1.json)
2. Open the generated Profile.java.

Notice that these CFTs should be of type Double:
![image](https://user-images.githubusercontent.com/6660853/85978517-78ac7580-ba11-11ea-8785-4b053ac79790.png)

Instead they are declared as Long:
![image](https://user-images.githubusercontent.com/6660853/85978586-98dc3480-ba11-11ea-92ca-40a2a43470d8.png)
