### ISSUE TITLE
Update EndpointInterface to load config function

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#150]
**Is your feature request related to a problem? Please describe.**
When parameters coming from a config.js file is loaded by the EndpointInterface, it should pass in the endpoint instance and the parameters to allow dynamic loading of parameters/urls

**Describe the solution you'd like**
Update the EndpointInterface.js template file with this: 
[EndpointInterface.js.txt](https://github.com/meveo-org/meveo/files/5141389/EndpointInterface.js.txt)

**Comment by czetsuya** [comment]
@tonysviews can you test in the current master branch?
