### ISSUE TITLE
Created CEI store as table but do not find it in the module screen lookup div

### ISSUE THREAD

**Issue by phubach** [meveo-org/meveo#151]
**Describe the bug**
Cannot find CEIs store as table in the module screen lookup div.

**To Reproduce**
1. Create CET store as table
2. Create CEI from CET 
3. Create a meveo module 
4. Click "Add Entity" button on "Module items" table
5. Choose "Custom Entity Instance" from "Entity Type" in popup
6. Cannot find CEIs

**Expected behavior**
CEIs from CET store as table should be found.

**Comment by ClementBareth** [comment]
@phubach please detail more

**Comment by phubach** [comment]
Module to import: [SOCIAL_LOOKUP_version-0_1_0.json.txt](https://github.com/meveo-org/meveo/files/5229530/SOCIAL_LOOKUP_version-0_1_0.json.txt)
Video to test: [Ticket151.zip](https://github.com/meveo-org/meveo/files/5229534/Ticket151.zip)
