### ISSUE TITLE
Script serialized in custom action

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#153]
**Describe the bug**
When exporting a module that contain a custom action and the corresponding script the created json contains the script twice, one copy in the custom action script property, one in the script instance

**To Reproduce**
1. create a script
2. create a CET with a custom action pointing to the script
3. create a module and add the CET and the script to it
4. export the module

**Expected behavior**
the script property of the custom action should refer the script but not serialize it

**Comment by ClementBareth** [comment]
I'm not sure whether it is a bug or if it was designed this way
