### ISSUE TITLE
Implement notification using Server Sent Events

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#16]
A javascript client should be able to subscribe to SSE notification when a specific CEI is modified or when a job is done, a script terminate its excecution, etc
This SSE chanel should also be used to implement chat and all notifications needs

**Comment by smichea** [comment]
Document and proposed implementation has been pushed,
check https://github.com/meveo-org/meveo/tree/feature/16-ServerSentEvents/meveo-admin/ejbs/src/main/java/org/meveo/service/notification

@czetsuya please implement the Rest API and GUI and commit some test in the form of a module

**Comment by czetsuya** [comment]
Postman collection for testing the web notification api.
[feature-16-sse-events.postman_collection.zip](https://github.com/meveo-org/meveo/files/4835776/feature-16-sse-events.postman_collection.zip)

**Comment by czetsuya** [comment]
Test module is in meveo-admin/src/main/resources/meveo-modules/SSE_TEST_version-<version>.zip

**Comment by czetsuya** [comment]
Already merged to develop branch.
