### ISSUE TITLE
Transitive imports of scripts are not working inside scripts

### ISSUE THREAD

**Issue by aponcon** [meveo-org/meveo#160]
**Describe the bug**
When creating a script that references another script, the first script should explicitely import all the scripts inside the related scripts.

**To Reproduce**
1. Create a Script A
2. Create a Script B that import A
3. Create a Script C that import B
4. C doesn't compile until you explicitely import A in C

**Expected behavior**
Transitive imports should work when importing scripts. In the example, C shouldn't explicitely import A.

**Comment by ClementBareth** [comment]
Fixed with #186
