### ISSUE TITLE
Automatically import all scripts inside the same package

### ISSUE THREAD

**Issue by aponcon** [meveo-org/meveo#161]
**Describe the bug**
Scripts that are in the same packages should be implicitely imported.

**To Reproduce**
1. Create a Script A in package a.b.c
2. Create a Script B in package a.b.c that needs A
3. Click on "Validate / Compile"
4. The script doesn't compile until you explicitely import A in B

**Expected behavior**
In the previous example, we shouldn't have to import A inside B as they are in the same package.

**Comment by ClementBareth** [comment]
Fixed with #186
