### ISSUE TITLE
Duplicated key exception while updating a CET

### ISSUE THREAD

**Issue by aponcon** [meveo-org/meveo#174]
**Describe the bug**
If the CET with Neo4J storage has a field referencing another Entity and defines a relationshipName for the field and if there's a CRT with this relationshipName, it will generate a conflict, more exactly a Duplicated key exception, making the update process to fail.

**To Reproduce**
1. Create a CET A
2. Create a CET B
3. Create a CRT C between A and B
4. Update the CET A with another field referencing B and with relationshipName C
5. The update of CET A fails

**Comment by ClementBareth** [comment]
Linked to https://github.com/meveo-org/meveo/issues/116
