### ISSUE TITLE
Force SQL table storage

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#175]
When we create a new CET that has SQL storage, enforce storedAsTable = true

**Comment by phubach** [comment]
Video to test: [Ticket175.zip](https://github.com/meveo-org/meveo/files/5238712/Ticket175.zip)

**Comment by phubach** [comment]
![comment](https://user-images.githubusercontent.com/9191276/93730590-7bbf9800-fbf3-11ea-8cdd-e6cf88dbc45a.JPG)
