### ISSUE TITLE
Updating a cft with default value fail

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#178]
**Describe the bug**
When updating a cft and default value is set it fails. Creating works.

**To Reproduce**
1. Create a new cet.
2. Create a new boolean cft set the default value to false.
3. Edit the cft, set the default value to true.
4. Click save.
5. An error will be thrown, false is incompatible with the numeric boolean value.

**Expected behavior**
The cft's default value should be updated.

**Comment by ClementBareth** [comment]
Fixed in commit a493e89e9300be0f28e750f9f8c0d956eca558cb
