### ISSUE TITLE
Updating of a script fails after execution

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#179]
**Describe the bug**
Script update fails after execution is invoke.

**To Reproduce**
1. Create a new script, using the default script is fine.
2. Execute the script.
3. Add a System.out.println("Hello"); line in the execute method.
4. Click save.
5. Lazy exception is thrown.

**Expected behavior**
The script should be save.

**Comment by ClementBareth** [comment]
Can't reproduce
