### ISSUE TITLE
Generated CET classes have incomplete fields

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#18]
When the java class of a CET is generated, some properties are not created.

Steps:
1. Import and install the following module: 
[InvestigationsModule_version-0_0_1.txt](https://github.com/meveo-org/meveo/files/4817333/InvestigationsModule_version-0_0_1.txt) _(rename to .json to import into meveo)_
2. Clone the meveo git repository: `git clone http://meveo.admin:meveo@localhost:8080/meveo/git/Meveo meveo-git`
3. Open the Investigation.java file at: `meveo-git/src/main/java/custom/entities/Investigation.java`
4. Notice that **firstName**, **birthDate**, and **placeOfBirth** and their corresponding accessors are not defined.

For reference, the Investigation CET has the following fields:
![image](https://user-images.githubusercontent.com/6660853/85365476-0393f880-b558-11ea-971b-ae63ecc2d721.png)

**Comment by czetsuya** [comment]
Fix is committed and tested on branch 15.
