### ISSUE TITLE
Child entity fields are not displayed

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#180]
**Describe the bug**
When adding a new child entity in a cei, the child entity's fields are not displayed.

Both CETs in the scenario below are of storageType=SQL.

**To Reproduce**
1. Create a new CET a with 1 CFT b.
2. Create a new CET b and add the CET a as a child entity.
3. Click save.
4. Open the CEI page and click Add new in CET a.
5. The popup table is empty.

**Expected behavior**
CFT b should be displayed and should be save.

**Comment by phubach** [comment]
Video to test: [Ticket180.zip](https://github.com/meveo-org/meveo/files/5326702/Ticket180.zip)

**Comment by czetsuya** [comment]
![image](https://user-images.githubusercontent.com/804528/95547673-10205c00-0a36-11eb-821b-17251aab3f2d.png)

@phubach I'm not able to edit the CET with child entity.

**Comment by phubach** [comment]
Video to test: [Fix180.zip](https://github.com/meveo-org/meveo/files/5390950/Fix180.zip)

**Comment by czetsuya** [comment]
In Testing.
