### ISSUE TITLE
Cannot save a script with maven dependency

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#181]
**Describe the bug**
Saving a script with a maven dependency does not work.

**To Reproduce**
1. Open the create a script page.
2. Add a maven dependency, for example apache commons io.
3. Import any class from apache commons io library.
4. Click save.
5. Script saving failed.

**Expected behavior**
The script should be save.

**Comment by ClementBareth** [comment]
Fixed in https://github.com/meveo-org/meveo/commit/63f3fb16f557d1cce75ff4987cbeebb31ac00120
