### ISSUE TITLE
 looks like filter do not work in CEI

### ISSUE THREAD

**Issue by phubach** [meveo-org/meveo#188]
**Describe the bug**
Cannot filter CEI.

**To Reproduce**
1. Create CET store as table
2. Create CEIs from CET
3. Filter a CEI
4. Click "Search" button
5. Cannot filter CEI

**Expected behavior**
CEI should be found and clean filters should be worked.

**Comment by phubach** [comment]
Module to import: [SOCIAL_LOOKUP_version-0_1_0.json.txt](https://github.com/meveo-org/meveo/files/5283434/SOCIAL_LOOKUP_version-0_1_0.json.txt)
Vide to test: [Ticket188.zip](https://github.com/meveo-org/meveo/files/5283436/Ticket188.zip)

**Comment by ClementBareth** [comment]
@phubach @czetsuya Just reviewed the code - it's not okay, don't merge it

**Comment by ClementBareth** [comment]
Rather than lower casing the field names, we should check why they are passed in lower case instead of upper case
