### ISSUE TITLE
[feat] Delete multiple CEI

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#190]
**Is your feature request related to a problem? Please describe.**
I want to select and delete multiple CEIs after applying a filter.

**Describe the solution you'd like**
Add a delete button at the end of the page and delete all the selected CEIs when pressed.

![image](https://user-images.githubusercontent.com/804528/94518208-16efe780-025c-11eb-96d6-55389df2a7c7.png)
*Here the delete button is missing.

**Comment by phubach** [comment]
Module to test: [SOCIAL_LOOKUP_version-1_2_0.json.txt](https://github.com/meveo-org/meveo/files/5333184/SOCIAL_LOOKUP_version-1_2_0.json.txt)
Video to test: [Ticket190.zip](https://github.com/meveo-org/meveo/files/5333185/Ticket190.zip)

**Comment by ClementBareth** [comment]
Implementation is OK
