### ISSUE TITLE
Upload size for jar file in GUI

### ISSUE THREAD

**Issue by phubach** [meveo-org/meveo#191]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ClementBareth** [comment]
[09:33] Clement Bareth
    I think it is meveo-admin-web/src/main/webapp/WEB-INF/undertow-handlers.conf
​[09:33] Clement Bareth
    max-entity-size(100000000) => maybe increase this ? 
​[09:33] Clement Bareth
    Or check if we can parameter it

**Comment by ClementBareth** [comment]
The feature is already implemented, and configurable using the parameter meveo.fileUpload.limitInMb
