### ISSUE TITLE
Add textarea CFT store as a long text (text blob) in postgres

### ISSUE THREAD

**Issue by phubach** [meveo-org/meveo#193]
**Is your feature request related to a problem? Please describe.**
Add a textarea CFT store as a long text

**Describe the solution you'd like**
- Add a textarea CFT store as a long text in dropdown of Data entry type.
- This field is displayed as a textarea in CEI.
- Data will be stored as text in postgres.

**Comment by phubach** [comment]
Video to test: [Ticket193.zip](https://github.com/meveo-org/meveo/files/5317477/Ticket193.zip)

**Comment by ClementBareth** [comment]
Implementation seems OK for me
