### ISSUE TITLE
Custom action enhancement

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#197]
Add a flag isApplicableToEntityList (false by default) and isApplicableToEntityInstance (true by default) . If the flag isApplicableToEntityInstance is true then it is the current behavior, we display the action button in the detail screen of the CEI then send the entity to the execute method in an "entity" param.

Now if this flag is set to isApplicableToEntityList then the button is also displayed on the list screen and called with selected entities uuids in "entities" param as a list of string

Currently the button appears always details screen, but it appears on list screen and only if i select entities, i guess it call the action once per selected entity... can you confirm ?

**Comment by smichea** [comment]
when dowloading locally INFRASTRUCTURE module from central installation went ok, then i changed the custom action of the SERVER CET so it is display both on list and detail page , but it is only displayed on detail page.


    when nothing is selected the execute method should be called without any param

    when some entities are selected (let say 10) a popup should ask confirmation with a message saying "The action will be called 10 times, one for each entity selected"

**Comment by czetsuya** [comment]
[ticket-197-custom-action-visibility.zip](https://github.com/meveo-org/meveo/files/5352225/ticket-197-custom-action-visibility.zip)
