### ISSUE TITLE
Custom action is not remove in display after delete

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#198]
When a custom action is deleted in GUI, the page is not refresh and it's still displayed after the action even though it's already deleted in the database. Refreshing the page removes it.

Steps:
1. Create a new CET
2. Create a custom action
3. Remove the custom action
4. Custom action is still displayed.

Expected Results:
The custom action should be deleted.

**Comment by phubach** [comment]
Video to test: [Uploading Ticket198.zip…]()

**Comment by phubach** [comment]
Video to test: [Ticket198.zip](https://github.com/meveo-org/meveo/files/5345977/Ticket198.zip)
