### ISSUE TITLE
Add an INSTALL and POST INSTALL event to Notifications

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#202]
**Is your feature request related to a problem? Please describe.**
When a new MeveoModule Notification is created, allow it to be configured to run a script when the MeveoModule is installed and after the MeveoModule is installed.

**Describe the solution you'd like**
When creating a new Notification and the Class Filter selected is MeveoModule, include an **Install** and **Post Install** event type.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by czetsuya** [comment]
I'm working on this ticket.

**Comment by phubach** [comment]
Postman to test: [Notifications.postman_collection.zip](https://github.com/meveo-org/meveo/files/5444383/Notifications.postman_collection.zip)

**Comment by ClementBareth** [comment]
@tonysviews this feature is useless

You can already link a script to a module.

See https://github.com/meveo-org/meveo/blob/c1d1cdb0420b7d5fa2cdce3944d0544568f0930b/meveo-admin/ejbs/src/main/java/org/meveo/service/script/module/ModuleScript.java

You have "preInstall" and "postInstall" methods

**Comment by ClementBareth** [comment]
I will document it & create a test suite

**Comment by ClementBareth** [comment]
And also create a test suite

**Comment by tonysviews** [comment]
@ClementBareth - It is useful if you need a script to run for ALL modules before/after install.  It is also useful if we want to run multiple scripts before/after install.

**Comment by ClementBareth** [comment]
Well ok ... @czetsuya I let you test the feature then

**Comment by ClementBareth** [comment]
I added some comments on your commits

**Comment by ClementBareth** [comment]
Please fill in the "TODO" section https://github.com/meveo-org/meveo/blob/d612e4662dc58143f96594da63c251b79b8a08e4/meveo-api/src/main/java/org/meveo/api/module/README.md

**Comment by czetsuya** [comment]
@phubach, I have added some comments on the tickets as well. Make sure to check in both GUI and API.

**Comment by phubach** [comment]
Video to test: [Ticket202.zip](https://github.com/meveo-org/meveo/files/5456746/Ticket202.zip)
