### ISSUE TITLE
"Secret" CFT type

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#203]
The content of the cft is never stored in clear in data-base

- [x] Add new SECRET custom field type
- [x] Create functions to encrypt / decrypt without a secret (always use the default secret)
- [x] Create function to hash a custom entity instance
- [x] handle the data serialization
- [x] service to see a encrypted value in clear
- [x] create role for seeing encryptyed value in clear
- [x] Handle SECRET custom field type in GUI : add a button to decrypt the field and see it in clear
- [x] Verify that export / import of custom entities with a secret field is functional

**Comment by smichea** [comment]
be careful that the encrpyted value should not depend on a secret as this can be exported and imported in a different meveo instance. so may be the encryption only depend in the uuid

**Comment by ClementBareth** [comment]
If there is no secret I don't really see the interest of the feature

**Comment by ClementBareth** [comment]
Maybe, in case of secret cfts, we should add the possibility to provide the secret during the import to decrypt the data ?

**Comment by smichea** [comment]
two interests :
1) a front user wont see the secret, even if he looks at the requests
2) a hacker that steals the db wont have clear fields

If we ask user to provide secret then it has to be stored too so scripts can use the secret value

**Comment by ClementBareth** [comment]
2) The code is open source so if we use only a salt and no secret, it is easy to retrieve this salt.

In the case we ask for the secret it is not stored, only given at the import time (the secret should correspond to the secret of the original meveo instance, otherwise the decryption will fail)

Anyway, if someone has access to the script creation, he can do absolutely anything

**Comment by smichea** [comment]
we dont want to protect the secret form a person that study the source code and can access the server. Just the 2 cases i gave in the above comment.
If we want more then it will be something else.

**Comment by ClementBareth** [comment]
Ok ...

**Comment by ClementBareth** [comment]
@smichea In a module export, should the secret fields be in clear ?

**Comment by ClementBareth** [comment]
[Secret-CFT.postman_collection.json.txt](https://github.com/meveo-org/meveo/files/5379322/Secret-CFT.postman_collection.json.txt)
