### ISSUE TITLE
CFT is not created with a number in the code and no error in GUI

### ISSUE THREAD

**Issue by phubach** [meveo-org/meveo#204]
**Describe the bug**
Create a CFT with a number in the code we get no error in GUI but CFT is not created.

**To Reproduce**
1. Create a CET
2. Create a CFT with a number in the code
3. Click "Save" button
4. CFT is not created and no error in GUI

**Expected behavior**
Message is displayed in GUI

**Comment by phubach** [comment]
Video to test: [Ticket204.zip](https://github.com/meveo-org/meveo/files/5347378/Ticket204.zip)

**Comment by czetsuya** [comment]
Must be implemented in the service layer so that API can be check as well.

**Comment by ClementBareth** [comment]
Moreover, the ontology pattern regex is configurable in the meveo-admin.properties settings, so the pattern you are using should be taken from it

**Comment by phubach** [comment]
Postman to test API: [CFT.postman_collection.json.txt](https://github.com/meveo-org/meveo/files/5400054/CFT.postman_collection.json.txt)
Video to test: [Uploading Fix204.zip…]()

**Comment by phubach** [comment]
Postman to test API: [CFT.postman_collection.json.txt](https://github.com/meveo-org/meveo/files/5400061/CFT.postman_collection.json.txt)
Video to test: [Fix204.zip](https://github.com/meveo-org/meveo/files/5400063/Fix204.zip)

**Comment by ClementBareth** [comment]
Seems ok to me
