### ISSUE TITLE
Associate a UserHierarchyLevel to a list of repository

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#209]
And restrict the repositories' data user access to this specific list.

If a user does not own the repo, he will get a 403 in PersistenceRs and the repo cannot be selected in custom entities GUI.

**Comment by czetsuya** [comment]
Fixes

- User group hierarchy level crud.
- Add user group selection in user detail.
- Add user group selection in repository detail page.

**Comment by czetsuya** [comment]
Testing:
1. Create 2 new databases in postgresql with name meveo_fr and meveo_ph.
2. Open the attached postman collection.
3. Run one by one until "Create repository - FR" test.
4. Edit user meveo.admin and set the user level to "PH".
5. Execute the last 2 tests, Inserts.
6. The last test should fail with "javax.ws.rs.ClientErrorException: User level does not have access to the repository.".

[feature-209-repository-user-level.postman_collection.json.txt](https://github.com/meveo-org/meveo/files/5451570/feature-209-repository-user-level.postman_collection.json.txt)
