### ISSUE TITLE
Add a map of script to CET/CRT that allow to associate to a list of event

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#213]
**Is your feature request related to a problem? Please describe.**
We are mostly using notification to trigger a script when an entity is created or updated. This works but is not the purpose of notifs. Notifs are used for aspect programming, like adding a logging feature for each entity creation.

**Describe the solution you'd like**
Add a map of script to CET/CRT that allow to associate to a list of event CREATE,POST CREATE,UPDATE,POST UPDATE,DELETE, POST DELETE,... a script

this could be a Map<int,List<ScriptInstance>>
where the int is binary field set for selected events
whatever the implementation you choose the idea is to have much better perfs than with notifs
when a CEI is persisted/deleted then we call the scripts that match the event by setting the "entity" param in the execute method

**Comment by ClementBareth** [comment]
I think it's better if we just use a single script with different functions (exposed using an interface)

This interface would be 

```
CrudEventListenerScript <I extends CustomEntity> {
    void prePersist(I entity);
    void preUpdate(I entity)
    void preRemove(I entity);
    void postPersist(I entity);
    void postUpdate(I entity);
    void postRemove(I entity);
}
```

**Comment by smichea** [comment]
looks like the script is correctly called when a CEI is created but not when a CET is updated
