### ISSUE TITLE
Deprecrate CustomEntityInstance service class

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#216]
- [ ] Move the utility functions to CEIUtils (if they are not already present)
- [ ] Use the CrossStorageService / CrossStorageApi instead of the CustomEntityInstanceService for the remaining references. 
  - ⚠️ The usage of CustomEntityInstanceService in the CrossStorageService itself should be kept

**Comment by czetsuya** [comment]
Checked references on PersistenceRs, CustomEntityInstanceListBean, CustomEntityInstanceBean, CustomFieldDataEntryBean and make the necessary updates.

Deprecated classes:
CustomEntityInstanceRs
CustomEntityInstanceApi
CustomEntityInstanceService

Dependent beans
CustomEntityInstanceListBean
CustomEntityInstanceBean
CustomFieldDataEntryBean

Not match to do here.
