### ISSUE TITLE
Zip dependencies of module when exporting it

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#220]
When a module has dependencies, automatically zip them when exporting it.

At import time, import all modules contained in the zip file. (maybe it is already the case)

At install time, first install dependencies before installing module (fail if they are not available)

**Comment by phubach** [comment]
Module file to import: [INFRASTRUCTURE_version-0_1_7.zip](https://github.com/meveo-org/meveo/files/5479460/INFRASTRUCTURE_version-0_1_7.zip)
Video and postman to test: [Ticket220.zip](https://github.com/meveo-org/meveo/files/5479464/Ticket220.zip)

**Comment by ClementBareth** [comment]
@phubach new requirements for this ticket : 

- This behavior has to be optional
- The transitives dependencies should also be included in the zip
- At import time, if a dependency is already installed with a different version, cancel the installation with error
- At import time, if a dependency is already installed with correct version, skip it
- At import time, if a dependency is not installed and not present in the zip (of if the file is not a zip), try to download for the "meveo instances" list
