### ISSUE TITLE
Refactor notification module

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#23]
1. All common codes for the class that extends notification api and service, should be refactor to it and not in the extending class to avoid code redundancy.
2. Implement missing dto, api, service, and rest classes.
3. Standardized the naming of entities, some have notification suffix, while some don't have.

**Comment by czetsuya** [comment]
@phubach I think we need a postman collection to test it thoroughly.

**Comment by phubach** [comment]
Postman to test: [RefactorNotification.postman_collection.zip](https://github.com/meveo-org/meveo/files/5236113/RefactorNotification.postman_collection.zip)
