### ISSUE TITLE
Unable to switch branches on git repository

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#24]
When the Social Profiling application is cloned by meveo into a locally mapped docker volume, it is not possible to switch branches because there are errors on the path for the submodules.

Steps:
1.  [Install meveo docker image](https://github.com/meveo-org/install/tree/master/docker/localhost)
> **Note:** Follow the steps under `Externalize all meveo files` to map the `meveodata` directory to a local folder on the computer.
2. [Install social profiling](https://github.com/webdrone-fr/module-socialprofile)
> **Note:** Since meveo is already installed via docker in step 1, start from `Install the WebAppRouter module`.
3. Open a command line or terminal window and go to the local directory that was mapped to `meveodata` in step 1.
4. Go to the social profile app's directory at: `{meveodata}/default/git/front-client.social-profiles` and checkout the develop branch.
```bash
git fetch
git checkout develop
```
The following error appears:

> fatal: not a git repository: /opt/jboss/wildfly/./meveodata/default/git/front-client.social-profiles/.git/modules/src/webapp/web_modules/mv-breadcrumbs

**Comment by ClementBareth** [comment]
@tonysviews Does pull works correctly ?
I can't reproduce
