### ISSUE TITLE
[GIT] Add "defaultBranch" and "isLocked" attributes

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#244]
- Default value for defaultBranch is "master"
- After the repository creation, the defaultBranch will be checked out
- If isLocked is true, then a user can't checkout an other branch than default one

**Comment by phubach** [comment]
Video and postman to test: [GitRepository.zip](https://github.com/meveo-org/meveo/files/5501116/GitRepository.zip)
