### ISSUE TITLE
Unable to add notification to module

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#246]
**Describe the bug**
When adding a notification to a module, an error is thrown in the logs.
`11:19:57,501 ERROR [org.meveo.admin.web.handler.CustomExceptionHandler] (default task-3) Exception: org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.meveo.model.module.MeveoModule.patches, could not initialize proxy - no Session`

**To Reproduce**
1. Install the [webapp-router-module](https://github.com/meveo-org/module-webapprouter/blob/master/meveo%20module/WEBAPPROUTER_version-0_4_0.json)
2. Create a new notification with the following details:
**code**: GenerateModuleWebApp
**classname** filter: org.meveo.model.module.MeveoModule
**event type filter**: Post install
**function**: org.meveo.script.GenerateWebAppScript
**function parameters**:
- **name**: module
- **value**: ${event}
3. Go back to **Modules > WEBAPPROUTER** and add the notification: **GenerateModuleWebApp**
4. Click **Save**

**Expected behavior**
The notification should be added to the module without errors.

**Additional context**
Here is the log file with the exception: 
[server.log](https://github.com/meveo-org/meveo/files/5493611/server.log)

**Comment by ClementBareth** [comment]
Will do

**Comment by ClementBareth** [comment]
@tonysviews the item is correctly added to the module, the error displayed is a warning, will investigate but it is not a blocking thing
