### ISSUE TITLE
incomplete module download from meveo instance

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#25]
when downloading and installing from GUI the [module  Webapprouter](https://github.com/meveo-org/module-webapprouter) from a remote meveo instance only the script got downloaded

**Comment by phubach** [comment]
[testDownloadModule.zip](https://github.com/meveo-org/meveo/files/4888426/testDownloadModule.zip)
Steps produce:
- Connect with 2 local
- Local 1: 
+ Create module from API then install module
[Import Module.postman_collection.zip](https://github.com/meveo-org/meveo/files/4888651/Import.Module.postman_collection.zip)
- Local 2: 
+ Go to Configuration> Meveo instances
+ Create meveo instance with url, username, password of local 1
+ Save meveo instance
+ Go to Configuration> Modules
+ Click Download and Install Module button
+ Select meveo instance
+ Check modules and download module
