### ISSUE TITLE
Add a link to Keycloak password modification page into the menu

### ISSUE THREAD

**Issue by aponcon** [meveo-org/meveo#252]
**Is your feature request related to a problem? Please describe.**
There's no easy way to update our own password from Meveo UI.

**Describe the solution you'd like**
A possibility would be to add an option in the Option button (on the top right corner of the page that looks like a gear cog) that links to the Keycloak password modification page.

Here the corresponding path:

```
/auth/realms/{{ KEYCLOAK REALM }}/account/password?referrer={{ CLIENT ID }}&referrer_uri={{ location of the user in meveo }}
```

**Describe alternatives you've considered**

**Additional context**

**Comment by czetsuya** [comment]
I have added a menuItem in the settings dropdown.

![image](https://user-images.githubusercontent.com/804528/99205882-cc6b0000-27f4-11eb-9992-4507efca4e2f.png)
