### ISSUE TITLE
[Module in Git] Handle addition / deletion operations for ScriptInstance

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#259]
For script compilation, use current module path as -sourcepath, and add other /src/main/java folder of other modules to the classpath

**Comment by ArthurGrenier** [comment]
## Specification for side effects
- Add a list of string sourcePaths in the parameters of the function `CharSequenceCompiler#compile(String, CharSequence, DiagnosticCollector<JavaFileObject>, boolean): Class <T>`
- Fix changements when the function is called
	- Retrieve the different Module dependencies and add them in the list
- In `CustomScriptService#onScriptRemoved(@Observer @Removed ScriptInstance scriptInstance)` call `BusinessService#removeFilesFromModule`
 - In `CustomScriptService#onScriptUploaded(@Observer @CommitReveived CommitEvent commitEvent)` add the script to its corresponding module where it was pushed
