### ISSUE TITLE
[Module in Git] Handle addition / deletion operations for Endpoint

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#260]

**Comment by ArthurGrenier** [comment]
## Description
Handle addition / deletion operations for Endpoints

## Specification
- Create an interface `BusinessServiceFinder` in `meveo-admin/ejbs`
- Implement this interface in `meveo-api`
- Call `BusinessService#moveFilesToModule` from within `MeveoModuleService#addModuleItem`
- Override `BusinessService#removeFilesFromModule` and `BusinessService#addFilesToModule` in `EndpointService`
- Add a commit at the end of these function
- Modify `BusinessService#addFilesToModule` and `BusinessService#removeFilesFromModule` to commit the .json files

**Comment by ArthurGrenier** [comment]
I'll continue #261 & #259 on this branch

# #261 Handle addition / deletion operations for CETs & CFTs
## Specification
- Override `BusinessService#addFilesToModule` in `CustomEntityTemplateService`
- In this function, create the java file and the json-schema in the dedicated module
     - Java file is called : "entityCode".java
     - json-schema is called : "entityCode"-schema.json
- Add a commit at the end of the function

# #259 Handle addition / deletion operations for ScriptInstance
## Specification
- Override `BusinessService#addFilesToModule` in `ScriptInstanceService`
- In this function, create the java file or js file in the dedicated module
- Add a commit at the end of the function
---
Clement will take care of side effect for those tickets

**Comment by ArthurGrenier** [comment]
## Specification for side effect
- Add `@TransactionAttribute(TransactionAttributeType.REQUIRES_NEW)` to required a new transaction before start the function
- Find the module of the updated endpoint
- Remove and add the json file in the dedicated module to update it
