### ISSUE TITLE
[Module in Git] Handle addition / deletion operations for CETs & CFTs

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#261]

**Comment by ArthurGrenier** [comment]
## Specifications for side effect
 - Change the function `CustomScriptService#findScriptFile` to get the corresponding script file if it's added to a module
 - Commit the updated files in `CustomScriptService#afterUpdateOrCreate` if it's added to a module
 - Change the function `CustomEntityTemplateCompiler#getCetDir` to get the directory of the file if it's added to a module
   - Add the CET in parameter of the function
   - Fix the broken code
 - Commit the updated files in `OntologyObserver#cetUpdated` & `OntologyObserver#cftUpdated` if it's added to a module
