### ISSUE TITLE
Modify /storages/repositories endpoint to return repositories accessible by the user making the request

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#263]

**Comment by czetsuya** [comment]
[feature-263-filter_repository_by_user_level.postman_collection.json.txt](https://github.com/meveo-org/meveo/files/5558521/feature-263-filter_repository_by_user_level.postman_collection.json.txt)

The attached postman collection contains tests that returns a list of repository base on the user level assign to the user sending the request.
