### ISSUE TITLE
NPE when retrieving repositories using /storages/repositories

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#264]
**Describe the bug**
A NullPointerException is thrown when accessing the /storages/repositories endpoint to retrieve the list of repositories

**To Reproduce**
1. Go to http://localhost:8080/meveo/api/rest/storages/repositories
2. An NPE is thrown in the logs and the following response is sent:
```json
{
  "status": "FAIL",
  "errorCode": "GENERIC_API_EXCEPTION"
}
```
**Expected behavior**
The list of repositories is returned

**Additional context**
Logs: 
[server.log](https://github.com/meveo-org/meveo/files/5550678/server.log)

**Comment by czetsuya** [comment]
@tonysviews did you populate the repository table? I'm not able to replicate the problem and I was able to successfully call the API using Postman.

![image](https://user-images.githubusercontent.com/804528/99355221-dff49480-28e2-11eb-962d-8a50f9824b95.png)
