### ISSUE TITLE
Add parameter to retrieve total count of CEI in PersistenceRs

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#272]
**Is your feature request related to a problem? Please describe.**
When retrieving a list of CEI using PersistenceRs, we should be able to add a parameter to optionally retrieve the total count.

**Describe the solution you'd like**
The response should include a count e.g.:
```js
{
  "count": 200,
  "result": [
    {... entity properties and values},
    {... entity properties and values}
  ]
}
```
**Describe alternatives you've considered**
N/A

**Additional context**
This will be used when generating the pagination controls on the frontend framework.

**Comment by ClementBareth** [comment]
@czetsuya I let you handle this : add a query parameter "withCount", which wraps the result in an new object if true, or that leaves the response the same as currently if false

**Comment by czetsuya** [comment]
Sample API calls are available in this postman collection. It serves as a test as well.

[feature#272-persistence list response.postman_collection.json.txt](https://github.com/meveo-org/meveo/files/5595049/feature.272-persistence.list.response.postman_collection.json.txt)

New query parameter withCount:
- false - nothing's change
- true - wraps the result into a new object:
{
  count: x,
  result: List<y>
}

**Comment by tonysviews** [comment]
The count should be the total count of the entities saved.  For example, on the frontend, we could have a pagination text of 👍 

1- 20 of 1234

in this example the count is: **1234**

**Comment by czetsuya** [comment]
Tested with Tony.
