### ISSUE TITLE
[CET Java class] Single child entity represented as list

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#275]
**Describe the bug**
When creating a cet A with child entity "b" of type B and storage type "single", the java class for A has a attribute `b : List<B>` instead of `b: B`

**Additional context**
The part of code to fix is the generation of the JSON Schema

**Comment by czetsuya** [comment]
It is by design. If the CFT type is CHILD_ENTITY, the storageType is automatically set to LIST:

if (entity.getFieldType() == CustomFieldTypeEnum.CHILD_ENTITY) {
            entity.setStorageType(CustomFieldStorageTypeEnum.LIST);
            entity.setVersionable(false);
        }

**Comment by czetsuya** [comment]
Problem is not in creating the class but in saving of entity. I've allow CFT of type CHILD_ENTITY to have a storage type of either SINGLE or LIST.
