### ISSUE TITLE
import zip module with subfolders in moduleFiles 

### ISSUE THREAD

**Issue by sophieperrineau** [meveo-org/meveo#281]
Note : if possible create a fix for latest stable release (but versionning is not an emergency)

I created a zip module with some files :  
```json:
[ {
  "active" : true,
  "code" : "WAPS",
  "description" : "WAPS Antipiracy cases analysis",
  "license" : "GPL",
  "currentVersion" : "0.1",
  "transient" : true,
  "inDraft" : true,
  "codeOnly" : false,
  "moduleItems" : [ ],
  "moduleDependencies" : [ ],
  "moduleFiles" : [ "/frontend/waps" ]
} ]
```
The zip contains a directory frontend/waps with subfolders.

The files are extracted to the target folder, but subdirectories are not created : they are part of the file names.
Example :
file named "ext-lib\admin_properties.js" instead of folder ext-lib containing file named "admin_properties.js"
![image](https://user-images.githubusercontent.com/48445076/102239796-838f8f80-3ef7-11eb-98f5-f712e494caa8.png)

**Comment by czetsuya** [comment]
[WebAppRouter.json.zip.txt](https://github.com/meveo-org/meveo/files/5722789/WebAppRouter.json.zip.txt)

Testing with this zipped module.

**Comment by ClementBareth** [comment]
@czetsuya I don't see any commit linked to this ticket, you did nothing ?

**Comment by czetsuya** [comment]
No commit for this ticket. It seems like it was fix in other tickets.

![image](https://user-images.githubusercontent.com/804528/103631590-22029400-4f7e-11eb-853b-97df08b341d1.png)

**Comment by sophieperrineau** [comment]
i tested again : the folder problem is not solved. It may be linked to the os ?
on my linux server, meveo-admin displays "Current directory: /frontend/waps" on your screenshot it is "Current directory: \frontend\waps"

**Comment by czetsuya** [comment]
This is what I have when testing in Ubuntu:

![image](https://user-images.githubusercontent.com/804528/103729609-cab30100-501b-11eb-8b02-6b570721461e.png)

**Comment by sophieperrineau** [comment]
the error occured because of unzip method (in meveo/FileUtils). Some path entry contained \
