### ISSUE TITLE
module install : transaction timeout

### ISSUE THREAD

**Issue by sophieperrineau** [meveo-org/meveo#284]
I'm trying to install a module with some cet, jobs and scripts and files to copy (zipped module).
The install (with option "overwrite") take a long time and it fails before the end.

No error is displayed on frontend. In logs, we can see the probem is linked to transactions, it seems that it timed out.

**Comment by czetsuya** [comment]
Module in question: https://webdronefr.sharepoint.com/sites/TeamDEV-DEV-Meveo/Shared%20Documents/DEV%20-%20Meveo/meveo-issue-284.zip

**Comment by czetsuya** [comment]
This is now fix. Fix could be related to my commit on #292.

**Comment by sophieperrineau** [comment]
tested again with version 6.14.0-SNAPSHOT => it's ok
