### ISSUE TITLE
Git exception when installing webAppRouter module

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#290]
When installing WebAppRouter module in a Meveo instance running on docker a Git exception is thrown.

**To Reproduce**
1. Run meveo using docker. 
2. Map the volumes to your local folders.
Here's a sample mapping:
meveo:
      image: manaty/wildfly-meveo:dev-latest
      container_name: meveo
      volumes:
        - /E/temp/meveo/docker/data:/opt/jboss/wildfly/meveodata
        - /E/temp/meveo/docker/logs:/tmp/meveo/binary/storage
3. Install the webAppRouter module available at https://github.com/meveo-org/module-webapprouter/tree/master/meveo%20module, use version 0.4.0.
4. Module installation failed with this error:
`2020-12-28 10:01:10,750 ERROR [org.jboss.as.ejb3.invocation] (default task-2) WFLYEJB0034: EJB Invocation failed on component GitRepositoryService for method public void org.meveo.service.git.GitRepositoryService.create(org.meveo.model.git.GitRepository) throws org.meveo.admin.exception.BusinessException: javax.ejb.EJBTransactionRolledbackException: Missing unknown e9ca9c310069ef87225689bec93fb8e5e166495d`

**Expected behavior**
WebAppRouter module should be installed.

**Additional context**
We already checked the docker container as well as the mapped folders and found no issue, specially related to permission.

**Comment by tonysviews** [comment]
Issue was resolved by replacing submodule with invalid commit hash in mv-template.
