### ISSUE TITLE
Cannot install a module with CFI and job instance

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#292]
**Describe the bug**
When installing a module with CFT, CEI, and JobInstance OptimistickLockException is thrown. See attached module for testing.

**To Reproduce**
1. Login to Meveo.
2. Click on Configuration / Modules.
3. Click Import from File and select the file attached to this ticket.
4. Click the newly imported module to open.
5. Click Install. On duplicate resource select SKIP.
6. StaleObjectException/OptimistickLockException is thrown.

**Expected behavior**
Module should be successfully imported.

Rename to .json

**Comment by ClementBareth** [comment]
The fix that has been made here is wrong : the JobInstance should be installed after the script instance and after the timer entity
