### ISSUE TITLE
403 error when retrieving entity from PersistenceRs

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#294]
**Describe the bug**
A 403 error is thrown when retrieving an entity using PersistenceRs

**To Reproduce**
1. Install WebAppRouter module. 
2. Install another module with CET.  WebAppRouter should generate new web application.
3. Access the web application via the browser. e.g. http://localhost:8080/meveo/rest/webapp/{module code}
4. Create a new entity.  It should automatically redirect to the update page.
5. 403 error is thrown in the logs.

**Expected behavior**
No the created entity details should be returned without errors

**Comment by czetsuya** [comment]
Use WebAppRouter and CaseManagement module I was able to generate a detail page without error:

![image](https://user-images.githubusercontent.com/804528/103731115-5e3a0100-501f-11eb-813d-d3ac756bbd7e.png)

**Comment by czetsuya** [comment]
I've run a test on this ticket using WebAppRouter and CaseManagement module but when accessing the webapp endpoint http://localhost:8080/meveo/rest/webapp/CaseManagement it only shows the default Address and Demo module and not CaseManagement.

**Comment by ClementBareth** [comment]
@tonysviews does your user has the rights to access the parituclar entity ?

**Comment by czetsuya** [comment]
@ClementBareth we are using the user meveo.admin.

**Comment by czetsuya** [comment]
@tonysviews @ClementBareth is this ticket still valid?
