### ISSUE TITLE
module-import - never drop existing tables

### ISSUE THREAD

**Issue by sophieperrineau** [meveo-org/meveo#296]
in current version,  try to import a module with cet stored in postgreSQL tables. If the cet is not defined in meveo, but the table exists in postgreSQL, then meveo 
 * drop the existing table (with the cet it was trying to install)
 * and then throws an exception which interrupts module installation
see CustomEntityTemplateApi line 195 (exception handler in create method)
=> if this error occurs, we should update the fields linked to this table, and check sequence, indexes ... and then finalize without errors the cet installation.

This errors occurs when the table exists, or when the sequence exists 

Moreover, we have to check that meveo never drops a table with data, or a sequence when rollbacking module installation

**Comment by ClementBareth** [comment]
Related to #333

**Comment by ClementBareth** [comment]
When deleting a CET, don't remove data (keep the table), unless it is explicitely specified
