### ISSUE TITLE
Implement more options in endpoint's URL

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#299]
Add an extra "pathTemplate" parameter in order to define the endpoint's url. Use the same syntax than swagger : https://swagger.io/docs/specification/2-0/paths-and-operations/ :
/users/{id}
/organizations/{orgId}/members/{memberId}
/report.{format}

Create a patch to build pathTemplate of existing endpoints.

Review unicity rule for endpoints creation (and implement changes in EndpointExecutionFactory) :
 * Allow two endpoints with same pathTemplate, and different http methods (post and get for example)
 * Allow two endpoints starting with the same path (first folder of path parameter) . for this use case, make sure "uk string" is unique

To perform this action, we could build a UK string :
POST:/path1/[^/]+/[^/]+/path2/[^/]+
this string is built from the pathTemplate, with :
 * "POST" = is the endpoint http method
  * [^/]+/ is a replacement for each path parameter 

This UK, can be used as a regex to find candidate endpoints in EndpointExecutionFactory.
If more than one candidate is found : 
 * keep only endpoints with the longest part before the first parameter
 * if more than on candidate is still selected :
 * remove all "[^/]+" of uk strings, and select endpoint with longest value ?

Example of UK Strings :
| pathTemplate | uk |
| :--- | :--- |
| /testEndpoint1/{reference}/manifest/{name}  | GET:/testEndpoint1/[^/]+/manifest/[^/]+ |
| /testEndpoint1/test/manifest/{name} | GET:/testEndpoint1/test/manifest/[^/]+|
| /testEndpoint1/{reference}/blobs/{name} | GET:/testEndpoint1/[^/]+/blobs/[^/]+|
| /testEndpoint1 | POST:/testEndpoint1|
| /testEndpoint1/{id} | GET:/testEndpoint1/[^/]+|

Other suggestions : "/[^/]+" could be a default replacement value, but we could allow user to define it (ex : limit a path parameter to numbers with "/[0-9]+"). If we do that, priorisation rules may have to be reviewed

--

what must be done in the GUI is this :

when the code is changed, basePath must be redisplayed (and should display the code if not overriden)

If the path has not be overriden
	
each time we add or remove a path parameter, this should reflect in the displayed path

If the path is manually changed in the text field, let say to  /{param1}/id/{param2}:
	
the runtime expection that could be throne by the Endpoint class must be displayed as error message
	if we add another path param param3, the path should be set by GUI to /{param1}/id/{param2}/{param3}
	if we then remove param2 from the path params, the path should be set by GUI to /{param1}/id/{param3}
	if we then remove param1 from the path params, the path should be set by GUI to /id/{param3}

it mean that if we remove "paramX" in the path params, then we should remove "/{paramX}" from the path, and if we add it then we add "/{paramX}" at the end of the path

**Comment by smichea** [comment]
@ClementBareth  pls review the back,
@czetsuya  please check the endpoint detail screen : we need to discuss it

**Comment by czetsuya** [comment]
[12:45 PM] Sebastien Michea
    
pathTemplate => i called it path
​[12:45 PM] Sebastien Michea
    did you see how it works in the Endpoint class ?
​[12:46 PM] Sebastien Michea
    by default the baseTemplate is the code of the endpoint
​[12:46 PM] Sebastien Michea
    and path is built from path param
​[12:46 PM] Sebastien Michea
    this allow to avoid migrating the current db
​[12:47 PM] Sebastien Michea
    now it is possible to rename the basePath
​[12:47 PM] Sebastien Michea
    this allow for instance 2 endpoint to have the same basePath if one is GET and the second is POST (as they cant both have same code)
​[12:48 PM] Sebastien Michea
    then path also is overridable 
​[12:49 PM] Sebastien Michea
    
this allow a default path /{​​​​​​​param1}​​​​​​​/{​​​​​​​param2}​​​​​​​ to be written for instance /{​​​​​​​​param1}​​​​​​​​/id/{​​​​​​​​param2}​​​​​​​​
