### ISSUE TITLE
 lock liquibase - unlock when starting

### ISSUE THREAD

**Issue by sophieperrineau** [meveo-org/meveo#300]
In some situation, the lock is saved and remains in postgres after Wildfly is stopped (or interrupted).

When this occurs, we have to connect to postgres to release the lock. 

The lock should be checked at startup, and release if needed => the goal is to avoid errors that may be difficult to analyze on production servers.

liquibase.lockservice.StandardLockService.releaseLock()

**Comment by ClementBareth** [comment]
has not happened recently => to re-open if it occurs
