### ISSUE TITLE
Handle non resolved maven dependencies

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#308]
**Describe the bug**
When adding a maven dependency to a script that cant be resolved the compilation fails with a NPE

**Expected behavior**
Error should be returned that precisely tells what are the failng dependencies

**Comment by smichea** [comment]
@ClementBareth  please review code proposal and test if correct

**Comment by smichea** [comment]
sorry the code formatting made a mess in the diff.
the methods i modified are 
addMavenLibrariesToClassPath
and getMavenDependencies

**Comment by ClementBareth** [comment]
I reported the modifications to avoid the formatting diffs
