### ISSUE TITLE
Permissions linked to a CRT : 

### ISSUE THREAD

**Issue by sophieperrineau** [meveo-org/meveo#313]
Roles and Permissions linked to a CRT should be simlar to permissions linked to a CET.
When i create a CRT, it creates roles instead of creating permissions : 

![image](https://user-images.githubusercontent.com/48445076/108070060-5d57ae80-7064-11eb-8562-30ea91fbbe30.png)

**Comment by sophieperrineau** [comment]
add the  role readAllCr and modifyAllCr (same logic than read/modify all ce) and add those role to admin role

**Comment by tonysviews** [comment]
implemented the creation of the roles and adding permissions on CRT creation:

![image](https://user-images.githubusercontent.com/6660853/135255333-209890fb-2b8d-455d-90db-24ba7bba3e1b.png)

**Comment by tonysviews** [comment]
When migrating existing CRTs, uninstall and reinstall the modules or individual CRTs.

**Comment by ClementBareth** [comment]
1/ The permission check should not be performed on the CRT CRUD, but on the CRT instances CRUD
2/ The patch is not in the right location

**Comment by ClementBareth** [comment]
I remove the checks on CustomRelationshipTemplateApi, but we still need to implement the permission check on cr instances
