### ISSUE TITLE
Jobs enhancements (UI) : threads pool size and summary

### ISSUE THREAD

**Issue by sophieperrineau** [meveo-org/meveo#314]
Add an option on UI to define the thread pool size for jobs of type "FlatFileProcessingJob".
the default value is 1.
This option is only available when parameter "Action on error" = continue
This option should be used to initialize "parallelism" value in org.meveo.admin.async.FlatFileProcessingAsync.launchAndForget

Add a column in executions listing : summary (this column has already been added to the job entity and is completed for FlatFileProcessingJob.
For other jobs, we could save parameters from the context in the summary

**Comment by tonysviews** [comment]
Testing results:
![image](https://user-images.githubusercontent.com/6660853/108654056-dcd0fc00-7502-11eb-80e2-04b1c24c1104.png)
![image](https://user-images.githubusercontent.com/6660853/108654067-e195b000-7502-11eb-8179-f2907246d6a4.png)

**Comment by sophieperrineau** [comment]
@tonysviews : is it possible to handle long text in summary ? (truncate the value in the list and make it clickable, same than report column)

**Comment by sophieperrineau** [comment]
long text issue is not easy to fix. We won't fix it now
