### ISSUE TITLE
endpoint security disabled

### ISSUE THREAD

**Issue by sophieperrineau** [meveo-org/meveo#317]
**Describe the bug**
I created a private endpoint. The probleme is that i exepected it to require authentification In reality, users request it without authentification. Could you check the conf and explain why it is public ?

More informations given during analysis :
There's a global property to disable all endpoints  security checks : ParamBean.getInstance().getProperty("endpointSecurityEnabled", "true")
Secutity should be enabled by default. On a new environments, it seems that this property is defined in system properties with the value "false" => it should not be intialized with this value

**Comment by tonysviews** [comment]
- default setting for meveo-admin.properties is set to true and documentation has been adjusted. [Endpoint documentation (develop branch)](https://github.com/meveo-org/meveo/tree/develop/meveo-admin/ejbs/src/main/java/org/meveo/service/technicalservice/endpoint)
- the feature works as expected:

using the following endpoint:

![image](https://user-images.githubusercontent.com/6660853/108797881-44507f80-75c7-11eb-9cde-20016681faf7.png)

If the feature is enabled:

![image](https://user-images.githubusercontent.com/6660853/108797888-4d415100-75c7-11eb-9ba4-66c898b3e955.png)

results in:

![image](https://user-images.githubusercontent.com/6660853/108797896-5500f580-75c7-11eb-8497-bb796ee66901.png)

If the feature is disabled:

![image](https://user-images.githubusercontent.com/6660853/108797944-77930e80-75c7-11eb-8506-ba97ffadb9f5.png)

results in:

![image](https://user-images.githubusercontent.com/6660853/108797961-837ed080-75c7-11eb-936b-a4bca4cb57fe.png)
