### ISSUE TITLE
Status module is wrong

### ISSUE THREAD

**Issue by phubach** [meveo-org/meveo#32]
In the module list screen, the status of some modules are wrong after installing module 

Steps:
1. Import and install some modules
2. Return the module list screen
3. Status wrong

Expected:
The status of module should be displayed correct.

**Comment by phubach** [comment]
pushed in https://github.com/meveo-org/meveo/commit/bd2f85742a8d8cf3d0f5d8ddeb66e1c4f3ed8960

**Comment by czetsuya** [comment]
Can we try a different approach for this? Clearing the em at service layer will disregard the cache.
