### ISSUE TITLE
Actions on modules should not be allowed with "Visualisation role"

### ISSUE THREAD

**Issue by sophieperrineau** [meveo-org/meveo#329]
I created a user who has administration "Administration Visualisation" permission.
this user should not be allowed to execute actions on the detail form of a module : 

![image](https://user-images.githubusercontent.com/48445076/116667675-c2048300-a99c-11eb-92ee-cdf39d52ea5c.png)

this user should view the list of users (it can see user groups, and user roles only)

the user i tested had the 2 following roles only - version 6.14.3 : 
![image](https://user-images.githubusercontent.com/48445076/116667969-1dcf0c00-a99d-11eb-8643-07fe9a83fa4d.png)

**Comment by sophieperrineau** [comment]
is it possible to check "Administration Visualisation", on all meveo-ui (pb with storage repositories ? cet deletion ? ....)
if some buttons are visible but action is not allowed (or it fails), we can delay the fix

**Comment by tonysviews** [comment]
I was finally able to test this issue and here are the findings:

![image](https://user-images.githubusercontent.com/6660853/118111731-affff700-b416-11eb-885b-8d8fec98218b.png)
![image](https://user-images.githubusercontent.com/6660853/118111744-b4c4ab00-b416-11eb-93de-d4800def735a.png)

A better UX design would be to hide the Install button and remove the other buttons on the module details page.

**Comment by tonysviews** [comment]
implement fix initially, there are two outstanding issues remaining:
`auditConfiguration` - its backing bean is not a BackingBean subclass so it doesn't have a canUserUpdateEntity method
`customizedEntities` - using canUserUpdateEntity will cause the page to fail with an exception

**Comment by tonysviews** [comment]
Merged to 6.15 branch - commit: c487d2e
