### ISSUE TITLE
[DOCKER] Add an environment variable to set the domain name

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#332]
This variable should then be written to the property named "meveo.admin.baseUrl" in the meveo-admin.properties file

**Comment by anaxdev** [comment]
@ClementBareth I added an environment variable for "meveo.admin.baseUrl" in the meveo-admin.properties file.
The variable name is `MEVEO_ADMIN_BASE_URL` and the default value is `http://localhost:8080/`.
In docker-compose.yml file, it can be defined like this:
```yaml
    environment:
      MEVEO_ADMIN_BASE_URL: https://<domain-name>/
```
> Note: \<domain-name\> should be replaced by the proper domain name.
