### ISSUE TITLE
CFT, and CRT errors when importing/exporting modules

### ISSUE THREAD

**Issue by sophieperrineau** [meveo-org/meveo#346]
When importing a module, the process is OK without errors , but the problems viewes in meveo-ui are  : 
1. CFTs : the attribute isFilter is not exported
2. CFTs : the attribute isFilter is not imported
3. CRT : the list of cft is not imported

**Comment by ClementBareth** [comment]
* The "isFilter" attribute is exported under the "filter" name in the json
* The cfts of the CRT does not seems to be automatically added to the module
