### ISSUE TITLE
Update PostgreSQL driver in CI

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#35]
**Describe the solution you'd like**
Upgrade PostgreSQL driver in the CI build to version 42.2.5. https://jdbc.postgresql.org/download/postgresql-42.2.5.jar.

**Comment by anaxdev** [comment]
Upgraded to the version 42.2.5

**Comment by anaxdev** [comment]
@czetsuya , you can test with docker image 'dev-latest' for your test.

**Comment by czetsuya** [comment]
Tested on both Ubuntu and Windows with the stack Java 11, WF 18, KC 10.
