### ISSUE TITLE
deleting a CFT doesnt delete the column

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#354]
When editing a CET "Wallet" stored in table, i had a CFT "application" of type Reference to an entity "Application"
but i realized the Application CET was not corectly stored (i wanted it stored in separate table too)

I the removed the CFT "application" from the "Wallet" entity, then deleted the "Application" CET , then recreated the "Application" CET this time with correct storage (new table should be the default value, not only on GUI but in the beans)

I then tried to add again the "application" CFT to the Wallet CET but got the error

```
Caused by: org.postgresql.util.PSQLException: ERROR: column "application" of relation "wallet" already exists
	at org.postgresql@42.2.5//org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2440)
```
which by the way is an incorrect log as "wallet" is not a relation but an entity

**Comment by ClementBareth** [comment]
This is the intended behavior from API. 

"relation" is the wording for table in postgres

I will fix to remove by default when using the GUI
