### ISSUE TITLE
Creating 2 endpoints with the same pattern

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#402]
Problem when i try to create 2 endpoints :
/rest/pg/v1/orders
and
/rest/pg/v1/methods

i created 2 endpoint with basepath 'pg' because we cannot use "/" in this baepath

pb is that only one of the 2 service can be called

we should be able to have 2 services that have same base path

we check for each of them that the path completly match

if we find only one endpoint that match we execute it

if we find 0, its a 404 like before

if we find more than one its a 404 also but error message "More than one endpoint found"

could you check if that can be fixed fast ? i have to prepare a demo

if not i ll do a workaround with a single endpoint with path pg and do the routing

**Comment by smichea** [comment]
my bad it seems we can correctly call the 2 endpoints
