### ISSUE TITLE
apitest can use persist POST but not persist GET to retrieve CEI

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#406]
**Describe the bug**
looks like the default account apitest/apitest can call any POST persistence service 
POST {{protocol}}://{{hostname}}:{{port}}/{{webContext}}/api/rest/:repository/persistence/:cet/list

but cannot call the GET one
GET {{protocol}}://{{hostname}}:{{port}}/{{webContext}}/api/rest/:repository/persistence/:cet/:uuid

only meveo.admin can do

**Comment by ClementBareth** [comment]
@smichea now, apitest should not have access to both endpoint

**Comment by ClementBareth** [comment]
However, when we first make the request, the user roles doesn't seems to be mapped

**Comment by ClementBareth** [comment]
Findings: on the first call, when using basic auth, the callerPrincipal is not of type keycloak, and the username is "anonymous"

**Comment by ClementBareth** [comment]
Seems that the first request cause to load some configuration, but does not apply it immediatly 

23:11:28,320 INFO  [org.keycloak.adapters.KeycloakDeployment] (default task-1) Loaded URLs from http://localhost:8081/auth/realms/meveo/.well-known/openid-configuration

**Comment by ClementBareth** [comment]
I can't seem to find a solution on this, so we just need to be aware that the first request will always fail unless a user log at each application start
