### ISSUE TITLE
allow to display child fields in pageconfiguration

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#407]
The pageConfiguration object is used in the persistence service list to select the returned fields of an entity.
when a field is a reference to an entity it currently display the uuid of the entity (or its identifier ?)
Improve this behaviour to allow display any other field of the child entity (whether its a single value, list , map,...)

for instance If a StartService has a mission of type Mission that has a owner of type User

then 
`"fetchFields":["mission.name","mission.owner"]`

would return
```
{
  'uuid':'12312312',
  mission:{
     'uuid ':'112122121',
     'name':'my mission name',
     'owner': '11222212'
  }
} 
```

and reccursively

`"fetchFields":["mission.name","mission.owner.name"]`

would return
```
{
  'uuid':'12312312',
  mission:{
     'uuid ':'112122121',
     'name':'my mission name',
     'owner': {
       'uuid':'11222212',
       'name':'the author'
  }
} 
```

**Comment by ClementBareth** [comment]
I added a small feature, to allow the usage of "*"

![image](https://user-images.githubusercontent.com/14770781/132103034-38c8b529-81fe-424d-9a4f-92a129102fa5.png)

**Comment by ClementBareth** [comment]
For now it does not work for get by uuid
