### ISSUE TITLE
allow to use pageconfiguration  in the GET entity by uuid persistence service

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#408]
in [Persistence services](https://github.com/meveo-org/meveo/tree/master/meveo-admin/ejbs/src/main/java/org/meveo/api/persistence) we can use pageconfiguration as the body of the POST service that return a list of entities

It would be also important to use it in the GET service that return an entity by uuid so we can choose the displayed fields.

**Comment by ClementBareth** [comment]
![image](https://user-images.githubusercontent.com/14770781/131743156-9cbdc18d-0c17-412e-98bc-bdda641b1e36.png)

**Comment by ClementBareth** [comment]
![image](https://user-images.githubusercontent.com/14770781/131743396-c63b47d0-a943-448d-bd57-0a3535958592.png)
