### ISSUE TITLE
Add list mode for persistence endpoint

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#425]
To use the persistence endpoint using a list, add the following header : 

![image](https://user-images.githubusercontent.com/14770781/134774435-c475fc12-5074-4070-88f6-077a285e3610.png)

![image](https://user-images.githubusercontent.com/14770781/134774447-cf01ddd7-59c5-459f-a32f-a31f165affb1.png)

**Comment by smichea** [comment]
to be able to reuse the response for the service that list entities, the cetCode should be optional in case it is set in the url 

```
POST {{protocol}}://{{hostname}}:{{port}}/{{webContext}}/api/rest/:repository/persistence/:cetCode
```

**Comment by ClementBareth** [comment]
I will then create an other for this case
