### ISSUE TITLE
Add Matrix type in generated POJO for matrix cfts

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#426]

**Comment by ClementBareth** [comment]
- Added type : org.meveo.model.customEntities.MeveoMatrix
- It is a parametirzed type that can take the following type arguments : Long / Instant / Double / String / Boolean
- Retrieve a value : use the `get(String... keys)` method
- Retrieve a value by closest match : use the `getClosestMatch(String... keys)` method
- Set a new value : use the `set(Object... keysAndValue)` method where the first parameters corresponds to the keys and the last parameters to the value

**Comment by smichea** [comment]
Retrieve a value : use the get(String... keys) method
Retrieve a value by closest match : use the getClosestMatch(String... keys) method

I thik it would be less confusing  to have keys names and values

**Comment by ClementBareth** [comment]
@smichea I don't understand your point
