### ISSUE TITLE
Improve log explorer

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#428]
currently the log explorer in meveo admin only allow to display some fix amount of lines.

It would be nice to be able to filter using a grep like function (this grep apply on server side)
and to set the log level (DEBUG,INFO,ERROR) of any class or package (this should send a command to wildfly)
and display the current log levels configured.

**Comment by ClementBareth** [comment]
For the log level setting part, I think it's better if we use the wildfly integrated console : 

![image](https://user-images.githubusercontent.com/14770781/136586062-c468420b-12a8-4044-a2fd-8e7ebeddf131.png)

**Comment by ClementBareth** [comment]
need to check this => https://commons.apache.org/proper/commons-io/apidocs/org/apache/commons/io/input/Tailer.html

**Comment by ClementBareth** [comment]
950875f5290cc4e220567fa3cbff2c9d188206ea
