### ISSUE TITLE
Logs not appearing on Chrome/Edge browser

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#440]
**Describe the bug**
The logs fail to display using Chrome or Edge browser,

**To Reproduce**
1. Open meveo on Chrome or Edge browser.
2. Select Execution > Logs > Logs explorer
3. Click READ or CONTINUOUS READING
4. The text area where the logs should appear remain empty.

**Expected behavior**
When the READ or CONTINUOUS READING button is clicked, the text area should be populated with the logs.

**Additional context**
The logs appear without problems on Firefox.

**Comment by czetsuya** [comment]
Unable to replicate in either local or account server.

**Comment by smichea** [comment]
cannot reproduce either
