### ISSUE TITLE
Implement missing http methods in endpoints

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#450]
Currently custom endpoint only allow GET and POST, implement also PUT,DELETE and PATCH

**Comment by smichea** [comment]
Please merge to master

**Comment by ClementBareth** [comment]
@smichea  I think it's merged already https://github.com/meveo-org/meveo/pull/461

**Comment by ClementBareth** [comment]
But for a reason, it is not visible on GUI, will check
