### ISSUE TITLE
Store module json on external table

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#467]
**Is your feature request related to a problem? Please describe.**
When a module is very large and we want to load it along with its module items in the same request, it causes an out of memory on postgres side because the json column is fetched every time

**Describe the solution you'd like**
The json should be stored in an external table and be lazily fetched in the MeveoModule model. We need to check where this source is used to make sure we fetch it. Also make sure the module source & the module items are never fetched in the same request.

**Comment by ArthurGrenier** [comment]
- Change tables MeveoModule with liquibase patch
- Add this table as @CollectionTable in MeveoModule

**Comment by ArthurGrenier** [comment]
https://github.com/meveo-org/meveo/commit/02a39881ceba72553767278a1797187f327b5832

**Comment by ArthurGrenier** [comment]
https://github.com/meveo-org/meveo/commit/786c2cd04727b3deb3497a9c9533b53a33450087
