### ISSUE TITLE
Custom Entity Template JSON Schema

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#47]
**Is your feature request related to a problem? Please describe.**
Currently, when a Custom Entity Template is created, a corresponding JSON Schema is created for it.  The schema should be validated made accessible through an api endpoint.

**Describe the solution you'd like**
 The schema should be made accessible through an api endpoint from client applications.

**Describe alternatives you've considered**
The generated JSON Schema may be made available through an API endpoint in meveo or through a module.

**Additional context**
Some additional things to consider include:

1. Make sure that references to child entities are linked correctly through $ref definitions.
2. Make sure that the generated JSON schema contains accurate properties corresponding to the CET attributes.

e.g.

- Import and install this module:  [InvestigationsModule_version-0_0_1.json.txt](https://github.com/meveo-org/meveo/files/4888086/InvestigationsModule_version-0_0_1.json.txt) _(remove .txt extension before importing)_
- There will be two CETs: Investigation and Location.
- The Investigation CET has two CFTs of type Location: places and visitedPlaces

Note the following issues:

- The string properties are defined with `maxLength = 0`
- The reference to the Location schema fails when validating the schema.  Use this to test: [schema-test.zip](https://github.com/meveo-org/meveo/files/4888141/schema-test.zip)

**Comment by phubach** [comment]
[CETJsonSchema.zip](https://github.com/meveo-org/meveo/files/4917568/CETJsonSchema.zip)

**Comment by tonysviews** [comment]
Just two issues:
1. When a string CET is added, the property should have no "**maxLength**" property.  Right now, it is defaulting to **255** characters.  **Please test what properties are generated with other types as well especially for range values.**
2. The **$ref** should not have a prefix, i.e. use "**Place**" instead of "**./Place**"

Updated **Investigations module** and **schema-test** project:  
[schema-test.zip](https://github.com/meveo-org/meveo/files/4923869/schema-test.zip)

**Comment by czetsuya** [comment]
An error is thrown when trying to import the attached module:

L'installation du module InvestigationsModule a échouée. Raison: org.meveo.admin.exception.BusinessException: java.lang.IllegalArgumentException: Table name 'Location' is a PostgresQL reserved keyword

**Comment by tonysviews** [comment]
@phubach @czetsuya - The generation of the JSON schema is okay, however as described in the description: 

> Describe the solution you'd like
The schema should be made accessible through an api endpoint from client applications.

What is the endpoint for fetching the generated CET JSON schema?  The sample postman sent by @phubach is retrieving the JSON schema of the Endpoint and not the one generated for the CET.

**Comment by phubach** [comment]
Update postman: [CetJsonSchema.zip](https://github.com/meveo-org/meveo/files/5033150/CetJsonSchema.zip)

**Comment by phubach** [comment]
Update postman to test: [CETJsonSchema.zip](https://github.com/meveo-org/meveo/files/5033918/CETJsonSchema.zip)
