### ISSUE TITLE
Functions on JS version seems not working

### ISSUE THREAD

**Issue by TaiTrien** [meveo-org/meveo#472]
**Describe the bug**
I write a simple function that returns a variable, I also configured the endpoint for that function already. But when I request to that endpoint, nothing is responded. The env that I used is the sandbox.

**To Reproduce**
Script path:
- Services/es5/org/meveo/script/redirectStore
Endpoint path:
- Services/Endpoints/REST/tip

**Screenshots**
<img width="1664" alt="Screenshot 2021-12-29 at 09 45 22" src="https://user-images.githubusercontent.com/32502320/147718805-d7e087f5-b780-4b76-b35c-04cf1fa89cfa.png">
<img width="853" alt="Screenshot 2021-12-29 at 09 46 04" src="https://user-images.githubusercontent.com/32502320/147718817-0464318b-e580-465a-9f2e-c4ff1231941d.png">
<img width="1235" alt="Screenshot 2021-12-29 at 09 47 52" src="https://user-images.githubusercontent.com/32502320/147718831-759414d1-71f6-4cb3-a675-66e45f3b3456.png">
<img width="855" alt="Screenshot 2021-12-29 at 09 48 16" src="https://user-images.githubusercontent.com/32502320/147718855-7605379f-7952-4e9b-8bf6-447b9f19f297.png">

**Comment by ClementBareth** [comment]
Hello @TaiTrien 

You need to write your value using the following syntax : methodContext,put('outputname', outputvalue)

**Comment by TaiTrien** [comment]
Hi @ClementBareth, it worked. Thanks a lot for your help

**Comment by TaiTrien** [comment]
Hi @ClementBareth, it worked. Thanks a lot for your help. But one more question, how can I get params from request in the script (I also configured the endpoint and the functions already)
<img width="705" alt="Screenshot 2021-12-31 at 09 57 42" src="https://user-images.githubusercontent.com/32502320/147800485-fbd0c09e-52b0-4d0c-9126-b41ecd4d8b14.png">
<img width="856" alt="Screenshot 2021-12-31 at 09 58 16" src="https://user-images.githubusercontent.com/32502320/147800497-deac6118-71aa-49b8-b60b-be08b297c7e9.png">

**Comment by TaiTrien** [comment]
> Hi @ClementBareth, it worked. Thanks a lot for your help. But one more question, how can I get params from request in the script (I also configured the endpoint and the functions already) <img alt="Screenshot 2021-12-31 at 09 57 42" width="705" src="https://user-images.githubusercontent.com/32502320/147800485-fbd0c09e-52b0-4d0c-9126-b41ecd4d8b14.png"> <img alt="Screenshot 2021-12-31 at 09 58 16" width="856" src="https://user-images.githubusercontent.com/32502320/147800497-deac6118-71aa-49b8-b60b-be08b297c7e9.png">

I found this "methodContext.get(paramName)" and it worked. When I return a HTML response, I can see the paramValue but when I try to log.info it, it has null value

**Comment by ClementBareth** [comment]
@TaiTrien You can either use the method you used, or even directly use the name of the parameter as a variable in the script (without declaring it)

I think you cannot log it as it is a JS variable, and the "log" object is a java object that can only print java object (JS strings seems to work so far)
