### ISSUE TITLE
CET Schema no longer being generated

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#483]
**Describe the bug**
When trying to retrieve the JSON schema of a CET, a 404 error is returned instead:

![image](https://user-images.githubusercontent.com/6660853/148746358-baad9f23-8666-4b42-b5bc-77ed7af63c30.png)

This is because the CET JSON schema was not generated and placed in the meveo git folder:

![image](https://user-images.githubusercontent.com/6660853/148746460-60e39c42-7daf-47a9-ba4d-7a166f10aa2f.png)

**Expected behavior**
When a CET is created/modified, the JSON Schema should be created/updated accordingly.  When the JSON schema is requested using the entityCustomization API, it should return the JSON schema.

**Comment by ClementBareth** [comment]
https://github.com/meveo-org/meveo/commit/109fd46e818b38944c053f1e1507c26b29742df5
