### ISSUE TITLE
Updated system property not picked up by script

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#493]
**Describe the bug**
When a system property is being used in a script and the value of the system property is changed, the updated value is being picked up by the script when the script is used after the update.

**To Reproduce**
1. Create a script that reads a system property using:
```java
    private ParamBeanFactory paramBeanFactory = getCDIBean(ParamBeanFactory.class);
    private ParamBean config = paramBeanFactory.getInstance();
    private String systemProp = config.getProperty("system.prop.key", "default prop value");
```
2. Check that running the script will retrieve the desired value.
3. Go to **Configuration** > **Settings** > **System settings**
4. Change the value of the system property.
5. Run the script again, and it will still retrieve the old value, instead of the new value.

**Expected behavior**
When the system property is changed, Scripts that retrieve those values should get the updated one.

**Comment by ClementBareth** [comment]
@tonysviews do you still have the issue ?

**Comment by tonysviews** [comment]
it is okay now
