### ISSUE TITLE
Possibility to target a repository on module installation

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#496]
- Associate repositories to a module, so that the CET / CRT tables and the CEIs are installed on these specific repo
- Associate repository to the CEI object to handle events
- Associate repositories to the CET / CRT

**Comment by smichea** [comment]
can you explain a bit more ?

**Comment by ClementBareth** [comment]
@smichea When we install CETs in a multi repo set up, we don't want to have the tables generated on all the repo that are known in our instance. And sometimes we don't even want to have it on the default repo

**Comment by ClementBareth** [comment]
Remaining tasks : 

- Associate a CEI to a repo
- Handle repos update for CET / CRT on GUI
