### ISSUE TITLE
CET based on parent CET not listed in module category

### ISSUE THREAD

**Issue by CrimSol** [meveo-org/meveo#507]
**Describe the bug**
A CET based on a parent CET is not listed in module CET list after module installation.

**To Reproduce**
1. Create CET with another CET as Parent.
2. Upload to Github
3. On clean instance of Meveo, pull and install module
4. See in module category list that child CET not listed although appears in CE customisation menu

**Expected behavior**
When installing a module, all entities should be listed to their CE category list, including child CET

**Screenshots**

**Additional context**

**Comment by ClementBareth** [comment]
Normal behaviour
