### ISSUE TITLE
Unable to import a CEI into a module

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#511]
**Describe the bug**
When adding a CEI to a module, it returns a PersistenceException.

**To Reproduce**
1. Open or create an  empty module by going to Configuration > Modules from meveo admin.
2. Click on "Add Entity"
3. Select Entity Type: Custom Entity Instance
4. Select the Custom Entity Template which contains the CEI we want to import
5. Click Search button
6. Click CEI to be added
7. The dialog disappears but the CEI is not added to the list

**Expected behavior**
After selecting the CEI, it should be added to the module's list of entities

**Additional context**
Sample error message:

Caused by: javax.persistence.PersistenceException: Error with query: select a.uuid, answer, question, "section" from {h-schema}frequentlyaskedquestion a 
params {}

**Comment by smichea** [comment]
fixed by #660 and #672 resolution
