### ISSUE TITLE
Jobs should be inactive during module installation

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#513]
**Is your feature request related to a problem? Please describe.**
When a module that contains a job instance is installed, it automatically activates the job.  This causes the module installation to fail if the job encounters any errors, like when the CETs or CEIs it needs are not yet installed, for example.

**Describe the solution you'd like**
When a module that contains a job instance is being installed (either using module json or git repo install or pull), the job instance should be inactive.  Then only activate or keep inactive depending on job instance active property when all other entities of the module are installed.

To help with this, when a job instance is added to a module, it should also store the active property in the module json.

**Comment by ClementBareth** [comment]
@tonysviews please test if it solves your problem

**Comment by tonysviews** [comment]
the job and the script related to it are no longer getting installed.
