### ISSUE TITLE
Error when uninstalling a module with chained jobs

### ISSUE THREAD

**Issue by QuentinTixier** [meveo-org/meveo#514]
**Bug description**
When a module has chained jobs, it can't be uninstalled and throw an error

> Échec de l'exécution de l'action. Erreur inattendue : Failed to uninstall/disable module item MeveoModuleItem [itemClass=org.meveo.model.jobs.JobInstance, itemCode=PPStatsUpdateMonthlySeederHitsJob, appliesTo=null, validity=null] (cause : ERROR: update or delete on table "meveo_job_instance" violates foreign key constraint "fk_following_job_id" on table "meveo_job_instance"n Du00E9tailu00A0: Key (id)=(133) is still referenced from table "meveo_job_instance".)

To uninstall the module we have to delete the jobs manually and then uninstall the module.

**To Reproduce**
1. Set up multiple chained jobs (4 in my case) in a module
![image](https://user-images.githubusercontent.com/89906202/159889100-d20dd99a-962c-4bc9-b5e0-ba4d141377aa.png)
![image](https://user-images.githubusercontent.com/89906202/159889130-1df905d3-ca94-42a6-b815-56d819554f6a.png)
![image](https://user-images.githubusercontent.com/89906202/159889166-dd127428-2d6d-46a4-bd8b-002a9ea2be04.png)
![image](https://user-images.githubusercontent.com/89906202/159889241-c23699ba-acfa-4f7a-84f2-091830cbcd80.png)
3. Uninstall the module
5. See error
![image](https://user-images.githubusercontent.com/89906202/159889416-72e03ddf-1ab1-4f68-97ec-4e4a40951817.png)

**Expected behavior**
Uninstalling the module works without issue and without having to delete the jobs manually

**Comment by ClementBareth** [comment]
I guess the problem should also happen on installation, we need to order the jobs
