### ISSUE TITLE
Unable to pull new endpoint

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#518]
**Describe the bug**
When an endpoint and script is added to a module's git repository and it is pulled from another meveo instance, there is a race condition between the endpoint and the script during module installation, where the endpoint is trying to look for the script before the script is installed.

**To Reproduce**
1. Install a module on a meveo instance using Git repository on a server or another machine.
2. On a different machine, install the same module and create a new endpoint and its associated script.
3. Push the new endpoint and script into github.
4. On the first machine, try to pull the updated endpoint and script.
5. An error is thrown that the script referenced in the endpoint does not exist.

**Expected behavior**
The installation of the module while pulling from git should install the script first before the endpoint.

**Comment by ClementBareth** [comment]
@tonysviews  can you test now ?

**Comment by tonysviews** [comment]
Works great now
