### ISSUE TITLE
add commit comment text box to meveo editor

### ISSUE THREAD

**Issue by nmfaraujo** [meveo-org/meveo#519]
add a textfield on the top menu of meveo editor , the value is saved in session. and meveo use that variable to append it to whatever commit he does.

this textfield shoud be a required value, when saving code

**Comment by babardev** [comment]
currently textfield is not required as discussed with @smichea . If developer will provide the issue url as a text in commit input box, it will append at the end of existing commit message.
_Add the script File : org.meveo.paytech.PaymentValidationServicein the module : mv-paytech : commit message

**Comment by babardev** [comment]
task is completed and code is pushed in attached branch.

**Comment by babardev** [comment]
fixed issue - commit message was set in GitClient class (ApplicationScoped). So commit message conflict was possible on dev env. now passing commit message to GitClient.commitFiles params
