### ISSUE TITLE
internationalization module

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#525]
Goal: we need an easy way to localize messages produced in scripts, and labels for entities lie CET, CFT, endpoints...

Solution:
Create a meveo module mv-internationalization that contain the following

CET: LocalizedMessage
  with CFT : 
    module: ref to module (mandatory)
    key : String (255) (mandatory)
    language: ref to Language (mandatory)
    value : LongText
A crudScript associated to the CET must make sure that after being created the LocalizedMessage is added to its module

1 scripts : Internationalizer
  
 Internationalizer script:
 The Internationalizer script with a static getInstance(Script scriptInstance, Map<String, Object> context) that return an instance 
 with the module corresponding to the scriptInstance and the Language that is either given by the http header "Accepted-Language" of the request present in the context (in case the calling script has been call from a rest endpoint) or the language associated to the Locale of the Principal of the logged in user. Then always add Java VM
locale.

get(String key, String defaultValue) -> calls get(key, null,defaultValue) 
get(String key, Map<String, Object> context) -> calls get(key, null,null) 
get(String key, Map<String, Object> context,String defaultValue) method:
Lookup step is to
    loop over the languages :   lookup LocalizedMessage for module, languages[i], key , if found go to Replacement step
    if no message found:
        if defaultValue is set then created the corresponding LocalizedMessage for the Java VM language and return the defaultValue and log an error.
        else return the key and log an error.
        
Replacement step : 
    if context is not null evaluate the value of the LocalizedMessage (as an EL) with the given context then return the result.
    else return the value as is.

Example 1 :

Let asssume that there is no LocalizedMessage in DB
```
public class HelloWorldScript extend EndpointScript {

    String helloWorldMessage;
    String welcomeMessage;

    public void execute(Map<String,Object> context){
       Internationalizer i18n = Internationalizer.getInstance(this,context);
       helloWorldMessage= i18n.get("my.message.key","hello world");
       welcomeMessage=i18n.get("my.secondmessage.key");
    }
}

```

helloWorldMessage will be "hello world" (MessageLocalizer create the missing LocalizedMessage);
welcomeMessage will be "my.secondmessage.key"

Example 2 :

Let asssume that there is 2 LocalizedMessage in DB:

| module  | key | language | value |
| "mymodule" | "my.message.key" | "en" | "I am ${age} year${age>1?'':'s'} old" |
| "mymodule" | "my.message.key" | "fr" | "J'ai ${age} an${age>1?'':'s'}" |

```
public class HelloWorldScript extend EndpointScript {

    String helloWorldMessage1;
    String helloWorldMessage2;
    String helloWorldMessage3;

    public void execute(Map<String,Object> context){
       Internationalizer i18n = Internationalizer.getInstance(this,context);
       helloWorldMessage1= i18n.get("my.message.key");
       helloWorldMessage2= i18n.get("my.message.key", Map.of({"age",1}););
       helloWorldMessage2= i18n.get("my.message.key", Map.of({"age",20}););
    }
}

```
Assume that we call the Script from an endpoint and that the http request contains the heade "Accepted-Language : Fr-fr"

helloWorldMessage1 will be "J'ai ${age} an${age>1?'':'s'}" 
helloWorldMessage2 will be "J'ai 1 an"
helloWorldMessage3 will be "J'ai 20 ans"

**Comment by fmunir1153** [comment]
Date: 20/04/2022
timespent*02:30 
-  for testing params as List<Object> instead of context as a second argument for composing a message with values.

**Comment by fmunir1153** [comment]
Date: 19/04/2022
timespent*03:21
For get methods without context implemented, Modified context to be a List<Object> instead of Map (as Object is just required to be inserted as array of values for STring format), right now just having issue with Date and trying to fix that, but after last - restart of machine there is a problem with deploying/running meveo from intelliJ, was looking into it for last hour, will just resume work later.

**Comment by fmunir1153** [comment]
Date: 20/04/2022
timespent*02:30

for testing params as List instead of context as a second argument for composing a message with values.

**Comment by fmunir1153** [comment]
This one is already done.
