### ISSUE TITLE
Script which imports another script fails to install

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#529]
**Describe the bug**

**To Reproduce**
1. Create a two scripts and import the first script from the second script.
2. Add both scripts to a module.
3. Push the module to git.
4. Delete the module or on a different meveo instance, try to install the module via git repository
5. A race condition may occur where the second script installs first, in which case, it throws an error that the first script does not exist.

**Expected behavior**
The module installer should check if there are dependencies to other scripts and install the dependencies first.

**Comment by ClementBareth** [comment]
@tonysviews you can test

**Comment by tonysviews** [comment]
It seems to be causing a bug on install or on git pull of module.

I am getting this error when installing a module from scratch:

```
01:30:55,887 DEBUG [org.meveo.service.notification.DefaultObserver] (default task-2) BusinessExceptionEvent handler inactivated { dateTime:Mon Apr 18 01:30:55 UTC 2022, meveoInstanceCode:, exception:org.meveo.admin.exception.BusinessException: java.lang.IllegalArgumentException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.meveo.api.dto.ScriptInstanceDto["importScriptInstances"]->java.util.ArrayList[0]) }
```

and getting this error when installing from git pull:

```
01:45:46,601 ERROR [org.jboss.as.ejb3.invocation] (default task-1) WFLYEJB0034: EJB Invocation failed on component MeveoModuleItemInstaller for method public java.util.List org.meveo.api.module.MeveoModuleItemInstaller.getSortedModuleItems(java.util.Collection): javax.ejb.EJBTransactionRolledbackException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: org.meveo.api.dto.ScriptInstanceDto["importScriptInstances"]->java.util.ArrayList[0])
```

Note that the error is just a DEBUG on clean install (which does means no error is shown on frontend) but is correctly reflected as an ERROR on git pull.

**Comment by ClementBareth** [comment]
@tonysviews  please test again.

**Comment by tonysviews** [comment]
still failing, encountering race condition

**Comment by ClementBareth** [comment]
@tonysviews please test again

**Comment by tonysviews** [comment]
this appears to have been fixed
