### ISSUE TITLE
Production export module

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#543]
Meveo intent is to be a development studio for enterprise apps. It brings flexibility in creating at runtime a entities, functions, endpoints,... things that jakartaEE servers do not allow.
This approach is good for development environments but not appropriate for staging or production environments.
A production environment need to be secure and performant hence the current Meveo ear is not adapted for production environment, as it allow by default to change datastore schema and bring unnecessary overhead on rest API.
Furthemore we want meveo to be agnostic of the technology so the goal is that a staging/production app could be a jakartaEE app, quarkus app, springboot app, php app, .Net app, C/C++ app, etc using any kind of framework flavor.
 
 The idea is therefore to create a meveo module mv-production-export that allow to generate for a given module the artifact necessary to build a production version of the app
 
 In a first stage we will create a war for a module that can be embeded in the current meveo ear but will expose rest API using dedicated Jax-rs resources.
 - [ ] #544

**Comment by masumcse1** [comment]
partially done few things.

[Meveo Ear File Information -- 543 -already done.txt](https://github.com/meveo-org/meveo/files/11320324/Meveo.Ear.File.Information.--.543.-already.done.txt)

--

**Comment by masumcse1** [comment]
[Meveo Ear File Information -- 543 updated 2023 .txt](https://github.com/meveo-org/meveo/files/11320327/Meveo.Ear.File.Information.--.543.updated.2023.txt)

**Comment by masumcse1** [comment]
Meveo ear file development process 
[Meveo.Ear.File.Information.--.543.updated.2023.txt](https://github.com/meveo-org/meveo/files/12422603/Meveo.Ear.File.Information.--.543.updated.2023.txt)

**Comment by masumcse1** [comment]
[meveo ear file test Guideline .txt](https://github.com/meveo-org/meveo/files/12590331/meveo.ear.file.test.Guideline.txt)

meveo ear file testing guideline
