### ISSUE TITLE
Return script result in onMessage

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#556]
Currently the webseocket endpoint return an hard coded "message correctly processed" each time the user send a message, it should instead return the result of the script execution

https://github.com/meveo-org/meveo/blob/d69688549cc6b5d5b94847e01a5f1da4dd5dd186/meveo-admin/ejbs/src/main/java/org/meveo/service/technicalservice/wsendpoint/WebsocketServerEndpoint.java#L147

**Comment by ClementBareth** [comment]
@smichea Looks like it is why I did for the webclient, thinking this was intended behavior. I will report this to websocket server then
