### ISSUE TITLE
Update adm_country table to ISO 3166-1

### ISSUE THREAD

**Issue by QuentinTixier** [meveo-org/meveo#558]
ISO 3166-1 https://datahub.io/core/country-list/r/data.json
adm_country currently has 237 countries (ISO has 249)
**14 missing country codes compared to ISO 3166-1:**
- Antarctica AQ
- Åland Islands AX
- Saint Barthélémy BL
- Bonaire, Sint Eustatius and Sab BQ
- Curaçao CW 
- Western Sahara EH
- Guernsey GG
-  Isle of Man IM
- Jersey JE
- Montenegro ME
- Saint Martin (French part) MF
- Serbia RS
- South Sudan SS
- Sint Maarten (Dutch part) SX
  
**2 more country codes compared to ISO 3166-1:**
- Yugoslavia YU ("Macedonia, the Former Yugoslav Republic of" in ISO)
- Netherlands Antilles AN (only Netherlands NL in ISO)

**Comment by ClementBareth** [comment]
To apply the fix, one must run the liquibase patch
