### ISSUE TITLE
Adding new CFT to CET does not update class in classpath

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#559]
**Describe the bug**
Adding a new CFT to a CET and then pulling the changes into another meveo instance fails to recognize the new CFT from a script.

**To Reproduce**
1. Create a new CET with a few CFTs. 
2. Create a new script that references (calls getter or setter) of the CET.
3. Save the CET into one module
4. Save the Script into another module.
5. Push both modules to github.
6. Install both modules to another meveo instance that is different from the one where the modules were created.
7. Update the CET by adding a new CFT and reference the new CFT from the script.
8. Push the changes to both modules into github.
9. Pull the changes for the module where the CET is included first.
10. Pull the changes for the module where the Script is included.
11. The pull will fail with errors in the logs showing that the new CFT still does not exist.

`Caused by: org.meveo.admin.exception.InvalidScriptException: cannot find symbol`

**Expected behavior**
When a new CFT is added and pulled into a meveo instance, it should update the compiled class in the classpath so that scripts that the new CFT may be available to scripts.

**Comment by tonysviews** [comment]
This might also be related to #561

**Comment by ClementBareth** [comment]
@tonysviews can you check again now ?
