### ISSUE TITLE
Pushing to the git repo does not update the class

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#561]
**Describe the bug**
If a java class is updated and pushed to the meveo git repo, the code is updated in the repo but it doesn't seem to get compiled and updated in the classpath.

**EDIT** - It also fails to compile script classes when pulling NEW scripts using Git pull from github.  It throws a script does not exist error.

This might also be related to https://github.com/meveo-org/meveo/issues/559

**To Reproduce**
1. Clone the git repository of a meveo module that has a script.
2. Edit the script, e.g. add a log statement.
3. Push it to the meveo git repo.
4. Run the script and check if the modification executes.

**Expected behavior**
The modification should execute.

**Current workaround**
After pushing the script into meveo, go to meveo admin and open the script there and save it.  This will compile the script and allow it to run with the changes in the script.

**Comment by ClementBareth** [comment]
Hello @tonysviews when creating the new script, did you also create the corresponding json file in /scriptInstances folder ?

**Comment by ClementBareth** [comment]
I tested creating a script and pushing, it's working. It is the same process than pulling

**Comment by tonysviews** [comment]
I just encountered it again.  Basically, after pushing, the script itself is updated, but when running the script, it will still run the older version of the script.  The only way to get the updated script to run is to open the script manually then save it.

**Comment by ClementBareth** [comment]
@tonysviews what is the context of execution ? What executes it ?

**Comment by tonysviews** [comment]
from an endpoint

**Comment by ClementBareth** [comment]
b21c2a49084d70e4f9fcc911046ec931efd67cf0

**Comment by tonysviews** [comment]
confirmed this is fixed
