### ISSUE TITLE
CEIs change UUIDs randomly

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#569]
**Describe the bug**
After saving a CEI is created with a custom UUID (one you manually add), the UUID changes every time the CEI is accessed.  It also cannot be retrieved using crossStorageApi using the UUID

**To Reproduce**
1. Create a CEI using CrossStorageApi and specify a UUID.
2. Save the CEI.
3. Try to retrieve the CEI using CrossStorageApi or try to access the CEI from admin GUI.
4. The UUID is different from the one used when creating the CEI

**Expected behavior**
The CEI should not have random UUIDs

**Screenshots**

https://user-images.githubusercontent.com/6660853/174693242-77e451bf-74a8-4898-83b8-7c7c705b6f63.mp4

**Comment by ClementBareth** [comment]
@tonysviews I can't reproduce, can you try from a new CET ? Maybe it's because of one of the fields

**Comment by tonysviews** [comment]
@ClementBareth - I updated the description with exact steps to reproduce.

**Comment by tonysviews** [comment]
Confirmed this is fixed
