### ISSUE TITLE
Git repo doesn't pull from new branch

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#570]
**Describe the bug**
When we try to change to a different branch and then try to pull from the new branch, it continues to pull from the old branch.

**To Reproduce**
1. Create a new repository linked to a github repository
2. Save the repository.
3. Open the repository and change the branch field on the form and save
4. Try to pull from the new branch.
5. It says the branch was successfully pulled but it actually pulled from the old branch.

**Expected behavior**
It should pull from the new branch.

**Comment by ClementBareth** [comment]
@tonysviews you will need to use the fetch function, then change branch name (you can use the droplist), then save and it will trigger the checkout
