### ISSUE TITLE
To load/filter results against multiple values of a field by using CrossStorageAPI

### ISSUE THREAD

**Issue by babardev** [meveo-org/meveo#599]
To load result sets from DB against multiple values of a field. like ids IN (21,22,25) 

crossStorageApi.find(defaultRepo, PurchaseOrder.class).by("productId", "IN", [21,22,25]).getResults();

**Comment by ClementBareth** [comment]
=> create a method "findByIds" in StorageImpl and CrossStorageService

Default implementation in StorageImpl is to aggregate the results from #findById method

**Comment by ClementBareth** [comment]
In CrossStorageRequest => add methods : 
- id(String id)  : CrossStorageRequest 
- ids(String id) : CrossStorageRequest

**Comment by ClementBareth** [comment]
@babardev I've set up the structure, you just need to implement SQLStorageImpl#findByIds now

But it can be done later, as of now it should work as it is. Maybe we can encounter performance issue, we'll implement the above method if needed

**Comment by fmunir1153** [comment]
Tried to look into it and analyzed code as I also needed it for some places.

**Comment by fmunir1153** [comment]
> @babardev I've set up the structure, you just need to implement SQLStorageImpl#findByIds now
> 
> But it can be done later, as of now it should work as it is. Maybe we can encounter performance issue, we'll implement the above method if needed

I have found that we can use it in this way to address this issue and it exist in meveo already, below is an example:

List<ChatConversation> chatConversations = crossStorageApi.find(defaultRepo, ChatConversation.class)
                    	.by("inList uuid", chatConversationUUIds)
                    	.getResults();

so it will check results against multiple Ids and it is working perfectly fine

@babardev 
@ClementBareth please see based on this can we close this ticket

**Comment by ClementBareth** [comment]
@fmunir1153 I think I can use this in the implementation of what i've done as well

Thanks for noticing this feature

**Comment by babardev** [comment]
> > @babardev I've set up the structure, you just need to implement SQLStorageImpl#findByIds now
> > But it can be done later, as of now it should work as it is. Maybe we can encounter performance issue, we'll implement the above method if needed
> 
> I have found that we can use it in this way to address this issue and it exist in meveo already, below is an example:
> 
> List chatConversations = crossStorageApi.find(defaultRepo, ChatConversation.class) .by("inList uuid", chatConversationUUIds) .getResults();
> 
> so it will check results against multiple Ids and it is working perfectly fine
> 
> @babardev @ClementBareth please see based on this can we close this ticket

thanks @fmunir1153 . We are OK with this.
