### ISSUE TITLE
Import module from internal file

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#6]
In the module list screen, rename the button "Import MeveoModule" to "Import from File" 
and add a button "Import from Internal file" that allow to import a module from a file stored in ./meveodata/default (it opens a file explorer)

**Comment by czetsuya** [comment]
You forgot: In the module list screen, rename the button "Import MeveoModule" to "Import from File".

**Comment by czetsuya** [comment]
This is incomplete: add a button "Import from Internal file" that allow to import a module from a file stored in ./meveodata/default (it opens a file explorer). It means we should be able to select a file from explorer and import the module.
