### ISSUE TITLE
filter items by module in meveo admin

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#605]
When we work on meveo we can select the module on which we are working you can see that on top right
that is useful because all CET, endpoint, script,... etc you create will automatically be added to that module.
Now what would be nice is that when you list CET, endpoint, script,... it display by default only the items that belong to the current module
this mean that we add a combo to all the filters that can filter by module and by default set it to the current mo

**Comment by mtnhan** [comment]
timespent*02:00 Nov 2, 2022
Investigate current implementation about getting module list

**Comment by mtnhan** [comment]
timespent*06:00 Nov 3rd, 2022
Investigate CET feature.

**Comment by mtnhan** [comment]
timespent*06:00 Nov 4th, 2022
Implement filter CET by selected module.

**Comment by mtnhan** [comment]
timespent*02:00 Nov 7th, 2022
Continue implement filter CET by selected module.

**Comment by mtnhan** [comment]
timespent*04:00 Nov 8th, 2022
Explore data schema of Meveo module.

**Comment by smichea** [comment]
You need to add a combo to the existing filters
and the value of the this combo is by default the current module
![image](https://user-images.githubusercontent.com/16659140/203179973-0e0154f1-97c0-459a-b073-f886d7ef25e0.png)
Note that there is also an empty value that allow to not filter by module
