### ISSUE TITLE
Add date build in meveo admin

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#624]
In the meveo info accessed through "about us" menu, we display the meveo version and build number.
Please add the build date.

**Comment by mtnhan** [comment]
timespent*02:00 Oct 31, 2022
Research getting maven build timestamp.
Investigate issue on maven build project: Failed to execute goal org.apache.maven.plugins:maven-clean-plugin:2.5:clean (default-clean) on project meveo-model: Failed to clean project: Failed to delete /home/meveo/meveo-model/target/generated-sources/annotations

**Comment by mtnhan** [comment]
timespent*04:00 Nov 1, 2022
Display maven build timestamp on about us page in meveo admin.
