### ISSUE TITLE
Custom Entities stored as table are not displayed in GUI

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#63]
**Describe the bug**
When CEIs are created they are no longer shown in the GUI

**To Reproduce**
1. Run meveo locally via docker.
2. Import and install this module: [ProfilesModule_version-0_0_1.json.txt](https://github.com/meveo-org/meveo/files/4923486/ProfilesModule_version-0_0_1.json.txt) _(remove .txt extension to import)_
3. Import this collection in Postman: [SP Endpoint Tests.postman_collection.json.txt](https://github.com/meveo-org/meveo/files/4923562/SP.Endpoint.Tests.postman_collection.json.txt) _(remove .txt extension to import)_
4. Import this environment in Postman: [meveo-local.postman_environment.json.txt](https://github.com/meveo-org/meveo/files/4923501/meveo-local.postman_environment.json.txt) _(remove .txt extension to import)_
5. Run the **New Profile** test a few times to create the Profile CEIs.
6. Run either the **List Profiles** or **Get Profile** test to check if the Profiles were created.
7. Go back to meveo admin and click the **SP Mock** menu and click **Profile**
8. Select the repository.
9. The list is empty

**Expected behavior**
When the custom entities are stored as table, they should be displayed in the GUI.

**Screenshots**
**Profiles created:**
![image](https://user-images.githubusercontent.com/6660853/87515999-45274780-c6af-11ea-9074-b2d9189735e0.png)

**Meveo GUI**
![image](https://user-images.githubusercontent.com/6660853/87516138-7d2e8a80-c6af-11ea-92d9-cb95eca1a6c7.png)

**Comment by ClementBareth** [comment]
When we create the data using the GUI, the data appeats in the listing

**Comment by ClementBareth** [comment]
Calling {{protocol}}://{{hostname}}:{{port}}/{{webContext}}/api/rest/default/persistence/Profile/list returns only the data added in GUI

**Comment by ClementBareth** [comment]
Ok i got the problem : in your script you are persisting to and retrieving from data stored in non-custom table (you use CustomEntityInstanceService instead of CrossStorageService)
However the CET is configured to be saved in custom table (separate table). So the GUI retrieves the data from dedicated table : where there is no data
