### ISSUE TITLE
Add filters when we select an entity

### ISSUE THREAD

**Issue by ArthurGrenier** [meveo-org/meveo#654]
When we want to select a field which makes a reference to another entity, It could be possible to filter the entities listed

For example here, we could search by the image name :
![image](https://user-images.githubusercontent.com/71335853/209555036-4403723f-b254-47c3-9b0a-abded8f8041e.png)

For now it can be long to search the entity you want or it may not be displayed at all

**Comment by smichea** [comment]
see #694
