### ISSUE TITLE
Invalid type of child entity CFT in CET detail page

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#657]
When a CET has a CFT of type Chid Entity, the type displayed in the CET detail page is "reference to <ReferencedEntity>".
It should be "child <ReferenceEntity>"

**Comment by tonysviews** [comment]
Child entities will now appear with a label prefix of: `Child entity - `.  e.g.
![image](https://user-images.githubusercontent.com/6660853/220850061-501502af-5fc6-422a-ab4f-ad80c73f4227.png)
