### ISSUE TITLE
Module suppression doesn't delete table in postgres

### ISSUE THREAD

**Issue by ArthurGrenier** [meveo-org/meveo#660]
### **Describe the bug**
When you delete a module in meveo (and select all suppression option) the tables and entries in postgres are not deleted

### **To Reproduce**
1. Install a module in the latest version of meveo
2. You can add some CEI in the CET's module
3. Delete the module of meveo
4. Check the meveo postgres database that there are still table and entries related to the module

### **Expected behavior**
Tables and entries related to the module should be deleted

**Comment by smichea** [comment]
@fmunir1153  please chek if it applies to latest-dev version

**Comment by fmunir1153** [comment]
@smichea it happens in latest meveo build. And it happened with multiple strange issues....  I am still discovering so that no other issue left in it

**Comment by fmunir1153** [comment]
timespent*01:13 March 28, 2023

Investigating/debugging to find out root cause, issue reproduced.
