### ISSUE TITLE
Add selection of files when commit

### ISSUE THREAD

**Issue by ArthurGrenier** [meveo-org/meveo#668]
Add a <p:pickList> on the page `gitRepositoryDetail.xhtml` with the unCommitedFile/UntrackedFile on the left and the files you want to commit on the right

Create new function in `GitClient#ListPendingChanges(GitRespository)` which return a set<String> of uncommited File and untracked File

In the function `GitRepositoryBean#Commit` changes to commit only the file on the right (stages file)

**Comment by ArthurGrenier** [comment]
timeSpent: 5

**Comment by ClementBareth** [comment]
The source list should be updated after we hit discard button
