### ISSUE TITLE
Add git url to module detail screen

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#683]
To make it easy for users to clone a module, add a "Git URL" field in the detail screen of a module, with a text field containing the url and button to copy it in clipboard.

![image](https://user-images.githubusercontent.com/16659140/219215522-b29061fb-af65-4cd7-b312-d733029a975e.png)

**Comment by fmunir1153** [comment]
timespent*02:00 March 20, 2023

Almost fixed it only clipboard copy with small icon on the right is left, will create a pull request tomorrow  hopefully

**Comment by fmunir1153** [comment]
Since this is of no use to the user as User has to replace the password to the url. Closing this ticket as per discussion with Sebastien
