### ISSUE TITLE
Automatic repository pull option on git repositories

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#684]
**Is your feature request related to a problem? Please describe.**
To enable CI / CD on module development, we should have a "automatic pull" field (like what has been done for https://github.com/meveo-org/module-webapprouter)

**Describe the solution you'd like**
- On the GitRepository entity, add an option to pull automatically.
- This option should be linked to a TimerEntity.
- When a GitRepository with a timer is created, or update, create the corresponding EJB job that will trigger the pull using default credentials. See JobInstanceService#scheduleJob for an example
- When a GitRepository with a timer is deleted, unschedule the job
- At startup, start the timers of all git repositories, Complete the ApplicationInitializer#initializeTenant method

**Comment by QuentinTixier** [comment]
timeSpent: 3

**Comment by QuentinTixier** [comment]
timeSpent: 5

**Comment by smichea** [comment]
the autopull flag is redundant, it is suffcient to test if the autopullTimer is null or not
