### ISSUE TITLE
incorrect maven dependency

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#691]
when a module contains a script that has a maven dependency, the generated pom.xml is incorrect.
The script dependency is written in a `<dependencies>` tag that is not inside `<dependencyManagement>` and the scope is `provided`.
When i manually move them to  `<dependencyManagement>`  and put scope `import` it works

**Comment by tonysviews** [comment]
@smichea - dependencies should now be inside dependencyManagement section of the pom.  To refresh pom, click the `Reinstall Module` button on the Git repository in Meveo admin.

**Comment by smichea** [comment]
can you please document the module page in https://github.com/meveo-org/meveo/tree/develop/meveo-api/src/main/java/org/meveo/api/module
also please make sure all the info in that readme are correct and complete

**Comment by smichea** [comment]
running `mvn install` from `facets/maven` now works.
I still cant compile from vscode but i will create another ticket for that
