### ISSUE TITLE
Added CEIs in a module are not restored with data on module update

### ISSUE THREAD

**Issue by fmunir1086** [meveo-org/meveo#696]
CEIs added to module are not restoring with data when re-installing a module (With Fresh install, its working good, but needed to verify with latest version)

1. Just add an entry in a CET
2. Got to module screen, and add that entry as CEI by:
          a) Clicking on add template button, popup appears select there Custom Entity Instance in first drop down 
          b) And selecting your CET there in second dropdown and press search button on popup, it will list your record/entry there
          c) click on your record/entry, popup closed and on module screen a CEI is added
3. Press Save Module button
4. Commit and push change to repo
5. Update this Git repo in meveo in another environment where this module is already there with old state.
6. You will see that CEI with UUID is restored but no data is there for that CEI only UUID is there.

Whole data records for all cfts should be restored on module update in above case, not UUID only and all cfts blank

![image](https://user-images.githubusercontent.com/122255544/225542742-10e43fa9-59b4-4025-94b7-f24c61be1703.png)

**Comment by fmunir1153** [comment]
@smichea there is one more observation that when we install module with no table in postgres, then CEIs are restored automatically with all proper data. Issue only happening if you have that table already there (as a result of at least one time entity owning module install)
