### ISSUE TITLE
Custom entity instance datalist fields are blank

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#71]
**Describe the bug**
The data list page of the custom entity instance is empty even if values are save.

**To Reproduce**
1. Create a CET
2. Create CEI for the CET
3. The list is empty

**Expected behavior**
The cei summary columns should be filled.

![image](https://user-images.githubusercontent.com/804528/87769088-adad2a80-c84f-11ea-96cd-b21c9835c72d.png)

**Comment by phubach** [comment]
[dataList.zip](https://github.com/meveo-org/meveo/files/4985866/dataList.zip)

**Comment by czetsuya** [comment]
Not all type of CFT are displayed even when summary is true. Try date, boolean, and other cft.

![image](https://user-images.githubusercontent.com/804528/88767143-c7356700-d1ab-11ea-9b84-6bc5c276d7d2.png)
