### ISSUE TITLE
cannot create CET with  CFT that are reference to User when CET has CrudScript

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#736]
looks like the pb comes from that
![image](https://github.com/meveo-org/meveo/assets/16659140/5bc28709-e4a5-466d-b963-14df25a9d6bc)
```
		try {
	       	Method getUuid = object.getClass().getMethod("getUuid");
			return getUuid.invoke(object);
		} catch(Exception ignored) {
		}
```

**Comment by tonysviews** [comment]
additional context:

This user entity is being associated to an NFCTag entity:
![image](https://github.com/meveo-org/meveo/assets/6660853/92570d71-1140-475e-a2ba-b5526f2c3434)

![image](https://github.com/meveo-org/meveo/assets/6660853/6d768e67-976a-446d-a626-453a0cda3b9d)


When it is passed into a CrudListenerScript:

![image](https://github.com/meveo-org/meveo/assets/6660853/afa28fdd-c38a-4fbd-a9c5-b6fd26b51e53)

The data in the owner entity is lost:

![image](https://github.com/meveo-org/meveo/assets/6660853/f9590e98-455e-4ed4-be2c-41fb72733970)

**Comment by tonysviews** [comment]
I think the fix for this is to move the following lines:

![image](https://github.com/meveo-org/meveo/assets/6660853/69d1782c-d0c5-40da-81a3-1b71ccc6d8f2)

**Comment by tonysviews** [comment]
When debugging the issue, it seems that during deserialization, the User type CFT will try to deserialize using JacksonUtil.  This results in a new User object.

I believe a possible fix for this is to move the following lines in CEIUtils:

![image](https://github.com/meveo-org/meveo/assets/6660853/3c80d228-5bd9-4c92-b210-fde2e089aa8c)
