### ISSUE TITLE
Custom action button in list screen

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#8]
Currently when we create a custom action on a CET it appears on the detail screen of a CEI.
It should also appear on the list screen but when clicked instead of setting the ENTITY to the entity of the detail screen we set it to a list of the entities selected (that could be empty)

**Comment by czetsuya** [comment]
There's still a bug for this ticket.

Inside the CET click Add new Action, fill in the form and click Save. The entity will be save, but it will refresh the detail page of the CET as if creating a new one.
