### ISSUE TITLE
Unable to delete an action inside a CET

### ISSUE THREAD

**Issue by czetsuya** [meveo-org/meveo#82]
**Describe the bug**
Inside the CET page, when delete button is press the custom action is not deleted.

**To Reproduce**
1. Create a CET
2. Add a custom action
3. Delete the CET
4. Custom action will not be remove in the GUI

**Expected behavior**
The custom action should be remove from the GUI and database.

**Comment by phubach** [comment]
[DeleteCET.zip](https://github.com/meveo-org/meveo/files/4971227/DeleteCET.zip)
