### ISSUE TITLE
Notification not triggered when creating CEI

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#88]
**Describe the bug**
Notification not triggered when a CEI is created from a CET that is stored as table

**To Reproduce**
1. Login to meveo admin.
2. Import and install the following module: [TestNotificationModule_version-0_0_1.json.txt](https://github.com/meveo-org/meveo/files/4970161/TestNotificationModule_version-0_0_1.json.txt) (delete .txt extension to import)
3. Create a new Entity GUI Config instance
4. Check logs to verify if the script executed

**Expected behavior**
The script associated to the notification should execute when a new Entity GUI Config instance is created.

**Comment by ClementBareth** [comment]
Actually, Your notification has to listen on the CustomTableRecord entity. But I agree that it should rather use CustomEntityInstance

**Comment by ClementBareth** [comment]
Ok, I just checked the code lately, and this has to be refactored anyway.
