### ISSUE TITLE
CET Audit Trail

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#89]
A boolean option to make CET auditable is available in both GUI and API. If this field is true, a new table must be created with the code of the cet prefix with audit_. For example, CET=computer, then our audit table must be audit_computer. This table is updated when an operation is executed on a particular CEI.

An icon field must be added in the CET computer for display.

The created table would have these columns : "uuid", "cei_uuid", "user", "date", "action", "field", "oldValue", "newValue"

We will be auditing the changes in the CEI and we will have one audit record per CFT updates. So if two CFTs are changed, then we will see 2 audit records in the audit table.

Example:
A CET person P is auditable, with CFT field "name" and "age".
- User U create an instance of P : a row is inserted in the table "audit_person" with user = u, date = now(), CEI_uuid = uuid of the created CEI, action = "CREATED".
- User U update the CEI with name = newName : a row is inserted in the table "audit_person" with same info as previous, but action = "UPDATED", oldValue = "" and newValue = "newValue"
- User U remove the CEI with name = newName : a row is inserted in the table "audit_person" with same info as create, but action = "DELETE"
- User U updated both the name and age field, 2 new entries will be created similar with the create info. But with different oldValue and newValue respectively.

*The audit table should be kept even when the CET table is deleted.

The GUI of CEI must be updated in order to show the audit history sorted from newest to oldest.
The same feature must be implemented in REST API.

**Comment by czetsuya** [comment]
1. Attached is a postman collectoin that creates CET, inserts data in CEI, and create audit logs.
[feature-89.postman_collection.json.txt](https://github.com/meveo-org/meveo/files/5087941/feature-89.postman_collection.json.txt)
2. Testing can be done in GUI as well.
