### ISSUE TITLE
Report CET Creation error 

### ISSUE THREAD

**Issue by smichea** [meveo-org/meveo#9]
When creating a CET with code "CASE" there is an error and i see the cause in the logs :
 Caused by: java.lang.IllegalArgumentException: Table name 'case' is a PostgresQL reserved keyword

this exception message should be displayed in gui (or returned in api)

also the CET should not have been created (as it appear in the list of CET it has probably been created in the cache)

**Comment by czetsuya** [comment]
Create a list of PostgreSQL reserved words and add it on the check not in the bean but in the service. Only add the words that are longer than 3 characters.
