### ISSUE TITLE
ScriptNotification script params not imported/exported in module

### ISSUE THREAD

**Issue by tonysviews** [meveo-org/meveo#90]
**Describe the bug**
When a ScriptNotification is added to a module, its script params are not imported/exported in the module.

**To Reproduce**
1. Open Meveo Admin and create a new Script (Services > Script > New)
2. Fill out the Script form and Save, e.g.
![image](https://user-images.githubusercontent.com/6660853/88532123-9d0e6880-d036-11ea-9383-cf50eaf0a656.png)
3. Create a new Script Notification (Services > Notifications > Notifications > New)
4. Fill out the notification details, making sure that we put a value under `Function parameters mapping`, then Save e.g.
![image](https://user-images.githubusercontent.com/6660853/88532377-1443fc80-d037-11ea-849e-1e89a45bb83d.png)
5. Create a new module (Configuration > Module > New)
6. Add the script and notification to it then Save. e.g.
![image](https://user-images.githubusercontent.com/6660853/88532611-7dc40b00-d037-11ea-9d15-a81339fed6df.png)
7. Go back to Modules then export the module.
8. Check the exported module JSON file and note that the `scriptParams` section is empty.

**Expected behavior**
The script params should be exported and should also be imported when the module is imported after.

**Comment by czetsuya** [comment]
ScriptNotification params are not exported as well.
