### ISSUE TITLE
CET Workflow

### ISSUE THREAD

**Issue by ClementBareth** [meveo-org/meveo#91]
Meveo workflow is used by applying it to the CET by choosing the CFT that will be the status.

A workflow is a set of transitions that allow to change the state of an entity in a controlled way.
The state is a CFT of type list of value of the CET. The workflow is made of a list of transitions.

A transition is a CFT that has:
- an origin state.
- a target state
- a evaluationEL
- a list of action

### How to apply a Workflow

A workflow is applied during CEI update by choosing CFT as state.

If we update the value of a CFT of a CEI and the corresponding CET has one workflow:
- If there is no workflow the update is persisted.
- If the workflow exists, then we check if there are transition from the previous state to the new one (before persisting the update), otherwise the update is refused.
- If transition exists, then we check each of the CFT's applicationEL (order by priority) and if none match we refuse the update.
- If one match then we persist the update and perform the actions.

Currently, the way workflow are applied is different: transitions have names and we execute a service that will change the state by applying a named transition. But for this implementation the user do not choose the transition, rather he chose the target state.

## Additional Requirements
- A service that returns a list of states for a given CET.
- A service that returns the target states from a origin state of a given CEI where applicationEL evaluates to true.

--

enable the workflow mechanism for CETs.

To do so, the user must tag a CFT as "status". This CFT must be a string list.

Once done, connect the existing workflow mechanism and listen on CEI changes

**Comment by phubach** [comment]
Here are script and testing [WF.zip](https://github.com/meveo-org/meveo/files/5100251/WF.zip)

**Comment by phubach** [comment]
Postman to test [CETWorkflow.postman_collection.zip](https://github.com/meveo-org/meveo/files/5102526/CETWorkflow.postman_collection.zip)

**Comment by smichea** [comment]
The association should be inverted : it is not the CET that own a list of WF, it is a WF that is associated to a couple (CET,CFT) where the CFT is a list of String (that will play the roles of state).

Example :
I create a CET "project" with the following CFT
- name, String
- createDate, Date
- description, String
- status, List of String (NEW,ONGOING,CLOSED) with default value NEW

Then i create a workflow with code "Projet_cycle", i need to choose a CET in a drop list (not a script), i choose "Person", then it list me in another dropdown all the CFT of Person that have type List of String  and a default value, i choose "status".
Then i can create the transitions and the actions.

When i update a CEI of type "Person" then in the beforeUpdate method meveo will check if the "status" value has changed, if yes then it will check if a WF exist for this  CET and CFT then apply it like written in the description of the ticket.

**Comment by phubach** [comment]
Here are postman and video to test: [UpdateCETWF.zip](https://github.com/meveo-org/meveo/files/5135969/UpdateCETWF.zip)

**Comment by czetsuya** [comment]
1. Remove the decision rules. This is not needed anymore.
2. I'm not able to edit a workflow, nor add/edit/delete a transition.
